### ISSUE TITLE
Newtonsoft.Json Exception

### ISSUE THREAD

**Issue by sjzamora86** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1033]
Hi All,

I'm pretty new using this System.IdentityModel.Tokens.Jwt; I want to use the latest version (5.3.0) but it is throwing Newtonsoft.Json exception when I try to call .WriteToken(jwtSecurityToken) which you can see below. 

**Target:** .Net 4.6.1
**System.IdentityModel.Tokens.Jwt:** v5.3.0
**Newtonsoft.Json:** v.11.0.2

Any help will be much appreciated.

System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'System.IdentityModel.Tokens.Jwt.JsonExtensions' threw an exception.
  Source=System.IdentityModel.Tokens.Jwt
  StackTrace:
   at System.IdentityModel.Tokens.Jwt.JsonExtensions.SerializeToJson(Object value)
   at System.IdentityModel.Tokens.Jwt.JwtHeader.SerializeToJson()
   at System.IdentityModel.Tokens.Jwt.JwtSecurityToken.ToString()

Inner Exception 1:
FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

Inner Exception 2:
FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

**Comment by GeoK** [comment]
Hi @sjzamora86,

How did you install the package?
Do you experience the same issue when you create a new project and install _System.IdentityModel.Tokens.Jwt_ via Package Manager Console:

> Install-Package System.IdentityModel.Tokens.Jwt -Version 5.3.0

**Comment by brentschmaltz** [comment]
@sjzamora86 @tschneideriii 	I don't see version 11.0.0.0 or 10.0.0.0 on nuget.org.

https://www.nuget.org/packages/Newtonsoft.Json/11.0.2

**Comment by sjzamora86** [comment]
Sorry guys for the late reply. 
It is working now for me, what I've done is:

- Remove reference to this library, 
- Delete all my packages (folder), 
- Restore NuGet
- Install it via console like @GeoK suggested

 And it works. I think it is conflicting on other packages that I installed.

**Comment by brentschmaltz** [comment]
good to know, thanks.

**Comment by samragriff** [comment]
I'm having the same issues, with any package I install to the project (B). The only way it works is if i update the newtonsoft in my other project A. (project A calls project B from an api controller). The problem for me is updating newtonsoft in project A - it breaks other things. Seems like because im calling the class from project A, it always uses the package version from package A. I have tried "Copy assemblies to different folders and use <codebase> to load them side-by-side (Requires strong names)" as outlined in https://michaelscodingspot.com/how-to-resolve-net-reference-and-nuget-package-version-conflicts/

But not working for me as dosent get triggered and seems like unnecessary workaraound.
