### ISSUE TITLE
IndexSources TFS 2015 build step fails with Microsoft.IdentityModel.JsonWebTokens.pdb

### ISSUE THREAD

**Issue by Saurbaum** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1098]
I'm seeing this in my overnight builds using the latest released build on nuget 5.3.0

Indexed source information could not be retrieved from d:\dev\Binaries\Win32\Release\Microsoft.IdentityModel.JsonWebTokens.pdb. Error: Symbol indexes could not be retrieved.

This is triggered before we publish our symbols to our server using https://msdn.microsoft.com/en-us/windows/desktop/microsoft.teamfoundation.build.workflow.activities.indexsources. and we are using Team Foundation Server 2015 Update 3.

If I'm reading this error message properly the pdb produced and packaged in nuget is made using a portable format.  Can you confirm that is the case and is there anything I can do to get around the error?

**Comment by brentschmaltz** [comment]
@Saurbaum is this happening for any other assemblies?

**Comment by Saurbaum** [comment]
So far it's only that one but it's entirely possible that the res of the IdentityModel assemblies have the same issue.

Unfortunately the Build step bails out on the first error so I'm unsure if it will affect the others.

**Comment by Saurbaum** [comment]
If I'm right https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/nuget#symbol-packages has the suggestions on how to distribute pdbs using nuget.

https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg

That then keeps the pdbs out of the nuget package and away from the Index Sources build step.

**Comment by brentschmaltz** [comment]
@Saurbaum we will try and get this into the next release.

**Comment by 9Rune5** [comment]
FWIW: This issue affects us as well. We are using TFS 2017, albeit not with the latest SP installed (long story).

**Comment by dozer75** [comment]
Stumbled into the same issue today and searched quite a bit on the net before I found this issue here.

Anyway, during that search I found that this seems to be an issue with the fact that the pdb file delivered with the nuget package is portable even for .NET targets. Not all external tools (like Visual Studio 2015, .NET versions 4.7.1, symbol server) supports this (see [portable information at the dotnet/core people](https://github.com/dotnet/core/blob/master/Documentation/diagnostics/portable_pdb.md)).

So I think that the solution here is the solution referenced [here](https://github.com/sendgrid/sendgrid-csharp/issues/494#issuecomment-317348955). It seems to have fixed problem with their nuget package.

**Comment by GeoK** [comment]
@Saurbaum We are going to ship our .pdbs in separate .snupkg packages (#1172). This should unblock you.
@dozer75 Thank you for chiming in. You are right, portable PDBs are not supported everywhere but the main advantage is that they can be created and read on all platforms.
