### ISSUE TITLE
JwtSecurityTokenHandler throws SecurityTokenInvalidSignatureException for spurious reasons

### ISSUE THREAD

**Issue by rodan01** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1168]
Why are you validating the signature of the JWT token before the body? The consequence is that you are throwing SecurityTokenInvalidSignatureException for spurious reasons. A token with wrong issuer is not a signature error.

Consumers of your library are using SecurityTokenInvalidSignatureException as an indication of key rollover, which means to refresh the metadata. If you throw that exception for everything, you're sending the wrong signal and causing performance problems.

For example, this issue in ASP.NET Core:
https://github.com/aspnet/AspNetCore/issues/10164

**Comment by brentschmaltz** [comment]
@rodan01 We don't trust anything in the token until the signature is validated. 

We throw SecurityTokenSignatureKeyNotFoundException when we were able to match the key in the jwt and the signature failed. https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/0e6d1bde65b158cf4edee41e9844f8bf5bf4c91f/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L972

If a valid issuer cannot be found we throw SecurityTokenInvalidIssuerException

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/0e6d1bde65b158cf4edee41e9844f8bf5bf4c91f/src/Microsoft.IdentityModel.Tokens/Validators.cs#L173

**Comment by brentschmaltz** [comment]
(copied from https://github.com/aspnet/AspNetCore/issues/10164 )
@rodan01 after talking to @Tratcher I see what you are saying. Reading the token then examining a Metadata cache of trusted issuers could solve this problem. Are you working with multitenant across identity providers { google, msft, FB, …} OR Azure tenants OR ALL of the above. I ask because we have some helpers on the way for Azure AD.

**Comment by brentschmaltz** [comment]
(copied from asp.net)
A multitenant Webapi accepts tokens from multiple authorities. It configures multiple JwtBearer schemes. It calls HttpContext.AuthenticateAsync() for every scheme in each request, using a policy or manually.

The problem is that the authentication process validates the token starting with the signature, that's inefficient because obviously a token from a different issuer won't pass. But even worst. when the signature validation fails, the metadata cache is cleared because it could be a case of keys rollover. So in each request, the metadata of all the other schemes is lost and they have to acquire it again in the next request.

Validation should start with the cheap stuff, issuer obviously.

Metadata should only be deleted if the issuer of the token matches the issuer of the scheme or if the issuer is not being validated, for example, for the Azure AD common endpoint. I don't know how you can solve that particular case.

Here snippets of the code that causes the problem.

validatedToken = ValidateSignature(token, validationParameters);
return ValidateTokenPayload(validatedToken as JwtSecurityToken, validationParameters);
AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet:src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs@master  Line 722

// Refresh the configuration for exceptions that may be caused by key rollovers. The user can also request a refresh in the event.
if (Options.RefreshOnIssuerKeyNotFound && Options.ConfigurationManager != null
&& ex is SecurityTokenSignatureKeyNotFoundException)
{
Options.ConfigurationManager.RequestRefresh();
}

**Comment by brentschmaltz** [comment]
@mafurman @RojaEnnam we should consider this with our ASPNET handler.

**Comment by brentschmaltz** [comment]
I believe this can be solved using the AadIssuerValidator.

To restate, until the signature is validated we don't make any assertions about the token.
We always have to validate the signature.
