### ISSUE TITLE
System.IdentityModel.Tokens.Jwt & Microsoft.IdentityModel.JsonWebTokens 5.5.0 are unsigned

### ISSUE THREAD

**Issue by williamBurgeson** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1231]
I have dropped System.IdentityModel.Tokens.Jwt into a project I am working on, and the latest default version was 5.5.0. When I pushed to our company's main repo (Git on bitbucket) I was told that the build failed with and error, which included the following info:-
...
Installing Microsoft.IdentityModel.JsonWebTokens 5.5.0.
[12:04:35]  Installing System.IdentityModel.Tokens.Jwt 5.5.0.
[12:04:35]C:\BuildAgent\work\...\[proj path].csproj : error NU3004: Package 'Microsoft.IdentityModel.JsonWebTokens 5.5.0' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
[12:04:35]C:\BuildAgent\work\...\[proj path].csproj : error NU3004: Package 'System.IdentityModel.Tokens.Jwt 5.5.0' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned.
...

I looked in another company project, which referenced IdentityServer4.AspNetIdentity version 2.5.0, which didn't have this problem. I could see the following chain of dependency:
IdentityServer4.AspNetIdentity@2.5.0 ->
IdentityServer4@2.5.0 ->
System.IdentityModel.Tokens.Jwt@5.3.0 ->
Microsoft.IdentityModel.JsonWebTokens@5.3.0

I replaced the nuget reference to System.IdentityModel.Tokens.Jwt to version 5.3.0 and this resolved the problem. Note that this also reverted Microsoft.IdentityModel.JsonWebTokens to 5.3.0.

This proves to me that the 5.5.0 version of these components do not have a valid signature if the git repo is set to declare that all nuget packages are signed.

Note that some related packages, Microsoft.IdentityModel.Logging and Microsoft.IdentityModel.Tokens appear to be OK at 5.5.0 without any error occurring.

<img width="398" alt="RangeBoard Nuget Dependencies" src="https://user-images.githubusercontent.com/1300727/62644484-1ef71480-b942-11e9-89f1-be915f6a8227.PNG">

Unfortunately I don't have admin rights to the setup of our company's GIT repo however as stated above, if it is stated in the repo that all packages are signed then 5.5.0 of these components are likely to break any project using them.

**Comment by brentschmaltz** [comment]
@williamBurgeson nuget.exe reports the signatures are fine.

E:\releases\Wilson\5.5.0\artifacts>\releases\nuget\nuget.exe verify -signature Microsoft.IdentityModel.JsonWebTokens.5.5.0.nupkg

Verifying Microsoft.IdentityModel.JsonWebTokens.5.5.0
E:\releases\Wilson\5.5.0\artifacts\Microsoft.IdentityModel.JsonWebTokens.5.5.0.nupkg

Signature Hash Algorithm: SHA256
Timestamp: 6/24/2019 1:10:48 PM

Verifying author primary signature's timestamp with timestamping service certificate:
  Subject Name: CN=Symantec SHA256 TimeStamping Signer - G3, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  SHA1 hash: A9A4121063D71D48E8529A4681DE803E3E7954B0
  SHA256 hash: C474CE76007D02394E0DA5E4DE7C14C680F9E282013CFEF653EF5DB71FDF61F8
  Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  Valid from: 12/22/2017 4:00:00 PM to 3/22/2029 4:59:59 PM

Signature type: Author
Verifying the author primary signature with certificate:
  Subject Name: CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
  SHA1 hash: F404000FB11E61F446529981C7059A76C061631E
  SHA256 hash: 3F9001EA83C560D712C24CF213C3D312CB3BFF51EE89435D3430BD06B5D0EECE
  Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 2/25/2018 4:00:00 PM to 1/27/2021 4:00:00 AM


Successfully verified package 'Microsoft.IdentityModel.JsonWebTokens.5.5.0'.

E:\releases\Wilson\5.5.0\artifacts>\releases\nuget\nuget.exe verify -signature System.IdentityModel.Tokens.Jwt.5.5.0.nupkg

Verifying System.IdentityModel.Tokens.Jwt.5.5.0
E:\releases\Wilson\5.5.0\artifacts\System.IdentityModel.Tokens.Jwt.5.5.0.nupkg

Signature Hash Algorithm: SHA256
Timestamp: 6/24/2019 1:10:42 PM

Verifying author primary signature's timestamp with timestamping service certificate:
  Subject Name: CN=Symantec SHA256 TimeStamping Signer - G3, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  SHA1 hash: A9A4121063D71D48E8529A4681DE803E3E7954B0
  SHA256 hash: C474CE76007D02394E0DA5E4DE7C14C680F9E282013CFEF653EF5DB71FDF61F8
  Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  Valid from: 12/22/2017 4:00:00 PM to 3/22/2029 4:59:59 PM

Signature type: Author
Verifying the author primary signature with certificate:
  Subject Name: CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
  SHA1 hash: F404000FB11E61F446529981C7059A76C061631E
  SHA256 hash: 3F9001EA83C560D712C24CF213C3D312CB3BFF51EE89435D3430BD06B5D0EECE
  Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 2/25/2018 4:00:00 PM to 1/27/2021 4:00:00 AM


Successfully verified package 'System.IdentityModel.Tokens.Jwt.5.5.0'.

E:\releases\Wilson\5.5.0\artifacts>\releases\nuget\nuget.exe verify -signature Microsoft.IdentityModel.Tokens.5.5.0.nupkg

Verifying Microsoft.IdentityModel.Tokens.5.5.0
E:\releases\Wilson\5.5.0\artifacts\Microsoft.IdentityModel.Tokens.5.5.0.nupkg

Signature Hash Algorithm: SHA256
Timestamp: 6/24/2019 1:10:43 PM

Verifying author primary signature's timestamp with timestamping service certificate:
  Subject Name: CN=Symantec SHA256 TimeStamping Signer - G3, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  SHA1 hash: A9A4121063D71D48E8529A4681DE803E3E7954B0
  SHA256 hash: C474CE76007D02394E0DA5E4DE7C14C680F9E282013CFEF653EF5DB71FDF61F8
  Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  Valid from: 12/22/2017 4:00:00 PM to 3/22/2029 4:59:59 PM

Signature type: Author
Verifying the author primary signature with certificate:
  Subject Name: CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
  SHA1 hash: F404000FB11E61F446529981C7059A76C061631E
  SHA256 hash: 3F9001EA83C560D712C24CF213C3D312CB3BFF51EE89435D3430BD06B5D0EECE
  Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 2/25/2018 4:00:00 PM to 1/27/2021 4:00:00 AM


Successfully verified package 'Microsoft.IdentityModel.Tokens.5.5.0'.

E:\releases\Wilson\5.5.0\artifacts>\releases\nuget\nuget.exe verify -signature Microsoft.IdentityModel.Logging.5.5.0.nupkg

Verifying Microsoft.IdentityModel.Logging.5.5.0
E:\releases\Wilson\5.5.0\artifacts\Microsoft.IdentityModel.Logging.5.5.0.nupkg

Signature Hash Algorithm: SHA256
Timestamp: 6/24/2019 1:10:43 PM

Verifying author primary signature's timestamp with timestamping service certificate:
  Subject Name: CN=Symantec SHA256 TimeStamping Signer - G3, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  SHA1 hash: A9A4121063D71D48E8529A4681DE803E3E7954B0
  SHA256 hash: C474CE76007D02394E0DA5E4DE7C14C680F9E282013CFEF653EF5DB71FDF61F8
  Issued by: CN=Symantec SHA256 TimeStamping CA, OU=Symantec Trust Network, O=Symantec Corporation, C=US
  Valid from: 12/22/2017 4:00:00 PM to 3/22/2029 4:59:59 PM

Signature type: Author
Verifying the author primary signature with certificate:
  Subject Name: CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
  SHA1 hash: F404000FB11E61F446529981C7059A76C061631E
  SHA256 hash: 3F9001EA83C560D712C24CF213C3D312CB3BFF51EE89435D3430BD06B5D0EECE
  Issued by: CN=DigiCert SHA2 Assured ID Code Signing CA, OU=www.digicert.com, O=DigiCert Inc, C=US
  Valid from: 2/25/2018 4:00:00 PM to 1/27/2021 4:00:00 AM


Successfully verified package 'Microsoft.IdentityModel.Logging.5.5.0'.

Please reopen if you can see what the issue is.

**Comment by williamBurgeson** [comment]
I'll have a chat with my boss to see what exactly the offending settings would be at our end, maybe it's an issue with git, one of its associated buld dependencies or our build engine, or just that we have misconfigured something - but I can confirm that 5.5.0 broke the build and 5.3.0 was ok

**Comment by brentschmaltz** [comment]
@williamBurgeson I had reviewed the 5.3.0 packages and verified the signing certs were the same.

I encourage you to find the root cause we may have an issue that we need to fix.
