### ISSUE TITLE
Microsoft Product License?

### ISSUE THREAD

**Issue by bodorjzsolt** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1246]
Hello,

In the file azure-activedirectory-identitymodel-extensions-for-dotnet/prototypes/AsyncTokenSample/AsyncWebAPI/Scripts/respond.js from version 5.5.0, this license is listed:

 _Microsoft grants you the right to use these script files for the sole
  purpose of either: (i) interacting through your browser with the Microsoft
  website or online service, subject to the applicable licensing or use
  terms; or (ii) using the files as included with **a Microsoft product subject**
  to that product's license terms. Microsoft reserves all other rights to the
  files not expressly granted by Microsoft, whether by implication, estoppel
  or otherwise._

What license applies on this file? In the ReadME it is stated that all code is licensed under MIT. Does MIT applies on this file as well? Can I use this file only in a Microsoft product?

Thanks,
Zsolt

**Comment by mafurman** [comment]
@bodorjzsolt This file was auto-generated when creating a Web API project using ASP.NET. If that's what you're trying to do, you should use the Web API template directly. 

This code isn't owned by us, but if you're interested in this file in particular you can find more information here:
https://github.com/scottjehl/Respond/blob/master/src/respond.js

This prototype was created a long time ago, and has since been removed from the dev branch. I would not recommend using this code as an example since it is outdated and the ASP.NET Web API template has changed.

**Comment by brentschmaltz** [comment]
@bodorjzsolt if this doesn't answer your question, please reopen.
