### ISSUE TITLE
Using an empty OIDC configuration

### ISSUE THREAD

**Issue by johnkors** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1307]
Hi,

I was told to ask here by @Tratcher in https://github.com/aspnet/AspNetCore/issues/17616#issuecomment-567545682.

I've written som authorization tests against my app startup for API protected by bearer tokens using JWT bearer tokens. In the test I wanted a way of overriding  hitting the OIDC Discovery document (.well-known/openid-configuration) to avoid network traffic, so I tried using a static configuration. Just by experimenting, I tried the empty OIDC configuration:

```csharp
var webHostBuilder = new WebHostBuilder()
    .UseStartup<Startup>()
    .ConfigureTestServices(s =>
    {
        s.Configure<JwtBearerOptions>(o =>
        {
            o.Configuration = OpenIdConnectConfiguration.Create("");
        });
    });
```

What surprised me, is that this made the test pass. I would have expected it to crash with "empty configuration", or similar. 

1) Is setting an empty OIDC configuration a valid scenario?
2) Will setting an empty OIDC configuration _bypass all jwt verification_ (issuer, signer, audience)?

**Comment by brentschmaltz** [comment]
@johnkors using a static configuration is a fine way to avoid the http traffic, most of our test use this. 
However, I would expect a token validation test to fail because no issuer, keys were found, so this surprises me. 
Can you share a bit about your tests?

Audience is not obtained from configuration, that is a relying parting setting, usually the clientid.

**Comment by johnkors** [comment]
Not sure why I did not get errors about an empty json before, but now I do :) Everything working as expected. Thanks for getting back to me!
