### ISSUE TITLE
IdentityServer4 compatibility

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1341]
Since Brent is asking here: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1291

We need good control over the shape of the rendered JWT - e.g. the header

https://github.com/IdentityServer/IdentityServer4/blob/99ce3764c2c0dacc4d8123ce4b0055261f9b228d/src/IdentityServer4/src/Services/Default/DefaultTokenCreationService.cs#L84-L116

Also the payload

https://github.com/IdentityServer/IdentityServer4/blob/a5b17e88857b60b5b7e5e6fcfe77287c41dbb49f/src/IdentityServer4/src/Extensions/TokenExtensions.cs#L32

So whatever you are doing, please make sure that this is all still possible.

**Comment by brentschmaltz** [comment]
@leastprivilege thanks for the heads up. Our message to our partners is that we don't want to break any significant scenarios. We want to be clear, we haven't lock any specific changes and are proposing a set of changes. We looked things over and came to a conclusion that to remove dependencies NewtonSoft could have breaking changes. We could create new types, rather than have some potential breaks. This would lead to parallel types and would in itself cause confusion.

We are looking to our partners to help us make the right changes.

**Comment by brentschmaltz** [comment]
@leastprivilege closing for now, if you seen any issues, please let us know ASAP as we are lobbying asp.net to internally use this release in the 5.0 release vehicle.

If we need any structural / api changes, it will be easier to get them in before 5.0.
