### ISSUE TITLE
Questions about JsonWebTokenHandler

### ISSUE THREAD

**Issue by Andrew-Webb** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1365]
Re. https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.JsonWebTokens/JsonWebTokenHandler.cs

1) Is this what you would recommend for creating and consuming JWTs in .NET Core (over previous implementations)?
2) Where is the sample code?
3) Where is the formal documentation?
4) Is it necessarily tied to Azure?  Or ActiveDirectory?  Can it be used (say) by a .NET Core 3.1 console app?

From spelunking around the web, it would seem that JsonWebTokenHandler was introduced in 2018 but not many people know about it and there's precious little information about it out there.

E.g. [this article](https://dotnetcoretutorials.com/2020/01/15/creating-and-validating-jwt-tokens-in-asp-net-core/) from January of this year only shows how to use `JwtSecurityTokenHandler`.  Ditto for many others.

Time to bring JsonWebTokenHandler into the limelight?

**Comment by brentschmaltz** [comment]
@Andrew-Webb we have developed JsonWebTokenHandler to fix some issues with JwtSecurityToken / Handler.

Most important it depends on 3rd party libraries.
It is much faster and less complicated.

However, internally asp.net takes a hard dependency on JwtSecurityToken. ISecurityTokenValidator must return a JwtSecurityToken or things will break.

We are working with asp.net so that 5.0 will be able to use this type.

**Comment by Andrew-Webb** [comment]
I take it you mean the new one _doesn't_ depend on 3rd party libs?  (e.g. Newtonsoft).

Faster is good, and less complicated is even better... `JwtSecurityToken` looked way overcomplicated to me, and I chose to avoid it.

I've gone with a more bespoke implementation for now, based on my fave library:- https://www.chilkatsoft.com/refdoc/csJwtRef.html for token creation, signing and verification, but have created an internal issue to consider switching to `JsonWebTokenHandler` in the future... when it seems more "official".

Thanks.

**Comment by brentschmaltz** [comment]
@Andrew-Webb yes thank you, doesn't depend on 3rd party libraries.

>  but have created an internal issue to consider switching to JsonWebTokenHandler in the future... when it seems more "official".

Internally within Microsoft, we were required at this level of the security layer to NOT take dependencies on 3rd party libraries. This occurred about a year ago, so major applications inside Microsoft have switched to using JsonWebToken / JsonWebTokenHandler.

I understand the '3rd' release rational. The JsonWebToken is definitely "official".

The reason that asp.net is not using that handler yet, is because we need to make internal changes to asp.net. 

It is hoped that we will make those changes by the 5.0 release.

**Comment by JoeMarkov** [comment]
Can I use JsonWebTokenHandler  to protect APIs in ASP.NET Core 5?

**Comment by Bellarmine-Head** [comment]
I have looked in vain (google search) for proper documentation on `JsonWebTokenHandler`.  I'm not sure if it's bundled in the ASP.NET Core version that's included with .NET 5.  I'm not even sure what package or what namespace it's supposed to live under in the .NET 5 world.  I continue to use https://www.chilkatsoft.com/refdoc/csJwtRef.html until the situation becomes clearer, and the documentation is fully there.

**Comment by jeevanbalanmanoj** [comment]
@Andrew-Webb  does this document help you? https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/ValidatingTokens#jsonwebtokenhandler

**Comment by Bellarmine-Head** [comment]
@jeevanbalanmanoj - looks like it could be useful, thanks.  I won't be changing our JWT-wrangling code now, but this could be a useful reference for future projects.

**Comment by udlose** [comment]
@brentschmaltz Any update on official MSDN documentation here?  I'm still trying to figure out why there's no `WriteToken` on `JsonWebTokenHandler`.  I see the `ReadToken`, but how do I write one to a string?

**Comment by HarelM** [comment]
Almost two years later, and I still can't figure out how to use this "new" token handler.
I'm trying to validate a token from a third party site and add the relevant claims to the context.
Any help and docs would be greatly appreciated.

**Comment by codelovercc** [comment]
Hi, guys, be careful when use `JsonWebTokenHandler`, it has some behavior is different to `JwtSecurityTokenHandler`. As I know `JsonWebTokenHandler` doesn't map outbound claim types.

`ClaimTypes.Role` is a string `"http://schemas.microsoft.com/ws/2008/06/identity/claims/role"`, when you call `JsonWebTokenHandler.CreateToken`, it will not map to JWT `role` claim.
