### ISSUE TITLE
System.IdentityModel.Tokens.Jwt/Validators.cs Expiration Issue

### ISSUE THREAD

**Issue by logitron** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#138]
File: System.IdentityModel.Tokens.Jwt/Validators.cs
Method: void ValidateLifetime(DateTime? notBefore, DateTime? expires, SecurityToken securityToken, TokenValidationParameters validationParameters)
Line: 217

There seems to be an issue in the way that it's looking at the expiration value.  The expire value is being checked to see if it's less than the current DateTime (minus 5 min skew value) and throwing an error if that's the case.  I believe this is backwards.

**Comment by brentschmaltz** [comment]
@logitron I think your are right it should be: expires > utcNow + clockSkew. 
Thanks.

**Comment by logitron** [comment]
You think the current version of the code is correct or you've implemented a change?

**Comment by brentschmaltz** [comment]
I think the current version is correct.

**Comment by logitron** [comment]
You are absolutely right.  I'm losing my sanity.  I would put out an issue for that, but I have yet to find its repository.  Sorry to waste your time on this.

**Comment by brentschmaltz** [comment]
No worries, it is the old double negative trick. It is always hard to grok. Even though I wrote the code, I had to go through the exercise of a creating a table...

Please don't let this influence your contribution to this project, keep the comments coming :-)

**Comment by laDanz** [comment]
I just had the same thoughts that this is implemented exactly the opposite way, even after reading this thread.
But when i finally realized this is for server side validation this made a whole lot more sense. I was using this for client side validation, where this is obviously the not desired implementation.
To still use this for client validation, since it is not possible to pass negative ClockSkew:
- set ClockSkew to TimeSpan.Zero
- and subtract the desired "ClockSkew" from the 'expires' DateTime
