### ISSUE TITLE
JWT aud field is optional, but validation fails when not present

### ISSUE THREAD

**Issue by hauntingEcho** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1402]
I'm currently attempting to verify a JWT received from Cognito, which [does not include the aud claim](https://stackoverflow.com/q/53148711/10100823).  As [the aud claim is optional](https://tools.ietf.org/html/rfc7519#section-4.1.3), this should be fine.  However, I'm receiving the error:

```
Error validating identity token: Microsoft.IdentityModel.Tokens.SecurityTokenInvalidAudienceException: IDX10214: Audience validation failed. Audiences: 'empty'. Did not match: validationParameters.ValidAudience: '[CENSORED]' or validationParameters.ValidAudiences: 'null'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateAudience(IEnumerable`1 audiences, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateToken(String token, TokenValidationParameters validationParameters, SecurityToken& validatedToken)
```

It looks like [that error is being thrown here](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/f5628e689e97b80fba3efe81fc33903076c97ad5/src/Microsoft.IdentityModel.Tokens/Validators.cs#L126), and 'empty' is just what`SerializeAsSingleCommaDelimitedString` gives back for [an empty list](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/f5628e689e97b80fba3efe81fc33903076c97ad5/src/Microsoft.IdentityModel.Tokens/Utility.cs#L45).

**Comment by hauntingEcho** [comment]
we intend to disable `validationParameters.ValidateAudience` as a temporary workaround, but would ultimately like to keep validation enabled for tokens which have the claim

**Comment by brentschmaltz** [comment]
@hauntingEcho you are correct that https://tools.ietf.org/html/rfc7519#section-4.1.3 specifies the claim as optional.

Both the OIDC and OAuth 2.0 indicate the need for check the value of this claim.
(OIDC - required, OAuth 2.0 - should).

Since our SDK is used mainly to validate inbound request, we validate the 'aud' by default.

OIDC: https://openid.net/specs/openid-connect-core-1_0.html#IDToken 
OAuth 2.0: https://tools.ietf.org/html/draft-ietf-oauth-jwsreq-20

Without checking the value of 'aud' the receiver is open to a forwarding attack where a token signed by a trusted identity provider but for a different host will be accepted.

We realize that some users may have other requirements, we added the ability to turn off validation, define a set of acceptable 'aud' values OR hook a delegate to give ownership to the application on a token by token case.

Please feel free to reopen or suggest additional API's.

**Comment by hauntingEcho** [comment]
That makes sense - it may be helpful to have a different error message in that case, since by default 'empty' gets censored (by PII settings) so it seems as though something's setting a literal 'empty' `aud`

**Comment by brentschmaltz** [comment]
@hauntingEcho could open an issue describing what improvements to the error message would be? We view error messaging as important, the fixes are easy and benefit can be large.

Customer opened issues have a bit more weight than internal :-)

**Comment by hauntingEcho** [comment]
opened as #1410 - thanks!
