### ISSUE TITLE
Usage of IDX13300 and IDX13107 is incorrect

### ISSUE THREAD

**Issue by keegan-caruso** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1455]
IDX13300 requires 2 arguments, It is passed into many FormatInvariant calls with only one argument.

IDX13107 in Saml2Serializer.ReadSimpleUriElement is used with 2 arguments and requires 3

Instead of raising an ArgumentException, it will raise a FormatException

**Comment by brentschmaltz** [comment]
@keegan-caruso we are planning a release with https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/1415 as the main feature.
Since we agree on the design yesterday, we could fix this add the analyzers and ship a new version.

@GeoK @mafurman @RojaEnnam @henrik-me this would keep us on mark for a release a month.
