### ISSUE TITLE
Breaking change in 6.7.0: Saml2AuthenticationContext.DeclarationReference no longer allows null values

### ISSUE THREAD

**Issue by nightkr** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1478]
See https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/0567929e7c7f4a299925f16a26d43ad5f8c60dc1#diff-d904bfa7b70e16ce90571f9a418a9362L123-L128, from #1458. 

Even if this is intentional (which I'm not sure about, given that the previous version explicitly allowed `null`s), 6.7.0 should be retracted and republished as 7.0.0 to be semver-compliant (as recommended by your own docs: https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/versioning).

/cc @catn8r

**Comment by brentschmaltz** [comment]
@teozkr the logic was that setting the value to null indicated an error.  The issue came to light when we realized the the default constructor would just fail.

It may be best, in this case to move back to the original case where the value 'value' is checked only when non-null and release 6.7.1.
I would rather roll back that than move to 7.x.

Does that make sense to you?

**Comment by nightkr** [comment]
Sounds good to me.

**Comment by brentschmaltz** [comment]
@teozkr cool, will make that happen. 
Thanks for finding and mentioning this, appreciate it.

**Comment by brentschmaltz** [comment]
@teozkr we dropped 6.7.1 with this rolled back. We will de-list 6.7.0.

**Comment by nightkr** [comment]
Thanks!

**Comment by brentschmaltz** [comment]
@teozkr thank you! As our SDK is used by other SDK's and used by other SDK's ... 
These type of breaks cause issues for users and we want to avoid that.

We as a team have realized that when we miss something like this, we have to leave it as is.
