### ISSUE TITLE
Invalid text in error messages (Int32 instead of number)

### ISSUE THREAD

**Issue by CheloXL** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1498]
Installed version: 6.7.1
Error text: "IDX10653: The encryption algorithm 'System.String' requires a key size of at least 'System.Int32' bits. Key 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey', is of size: 'System.Int32'. (Parameter 'key')'"

As you can see, everything is wrong with what I guess are placeholders in the error string. Instead of "hmac-sha256" I'm getting "System.String". The same for the key sizes (128 should be instead of System.Int32).

Not sure if previous versions have the same issue. Using it in a console netcoreapp3.1.

**Comment by keegan-caruso** [comment]
Thanks for reporting this.

This looks like an instance were we are aggressively filtering out potential [PII](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII)

**Comment by rwatjen** [comment]
@keegan-caruso: I ran into a similar issue where the 'kid' was the problem, and no amount of searching let me know that the error message with "kid: 'System.String'" was because of the PII scrubbing. (Btw: I don't consider the key ID as being PII - it is after all public information that can be retrieved from the well-known URL from the OIDC provider).

It would be nice if the PII scrubbed error messages contain information that leads the developer to the reason for the exception messages having the type names instead of the real data. Like @CheloXL I thought it was a bug in the library.

**Comment by keegan-caruso** [comment]
@rwatjen thank you for adding perspective.

You might be interested in the following items

#1274
#1452
#1427

This looks covered by existing issue so I'm going to close the issue.
