### ISSUE TITLE
make internal JSON classes public

### ISSUE THREAD

**Issue by trivalik** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1502]
Several classes are usefull without out juse of JWT.
For example in Microsoft.IdentityModel.Tokens the class Microsoft.IdentityModel.Json.JsonConvert or Microsoft.IdentityModel.Json.JsonConverter<T>. These classes existing in Newtonsoft.Json as public.

**Comment by brentschmaltz** [comment]
@trivalik we are going to be moving to the new System.Text.Json API's.
The internal JSON work is just a stop gap as we were hitting some back-compat issues.

**Comment by chwarr** [comment]
Is there an issue for migrating to System.Text.Json? I'd like to track that so that I can update my product's code when ever that happens.

At the moment, I'm using [`System.IdentityModel.Tokens.Jwt.JsonExtensions.SerializeToJson()`](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/30c16ab82cf4338c6d6e04a5d4094795aa83c587/src/System.IdentityModel.Tokens.Jwt/JsonExtensions.cs#L88-L96).

(Related: [#1475, OpenIdConnectConfiguration not serializing properly](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1475))
