### ISSUE TITLE
JwtSecurityTokenHandler.DefaultMapInboundClaims static property considered harmful

### ISSUE THREAD

**Issue by IanKemp** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1537]
https://blog.ploeh.dk/2020/10/05/fortunately-i-dont-squash-my-commits/

To paraphrase, `Global variables are evil.`

`JwtSecurityTokenHandler.DefaultMapInboundClaims` is a global variable. It should not exist. Instead there should be an **instance** configuration method or option that can be hooked in ConfigureServices, i.e. following the standard pattern for configuration in ASP.NET Core.

The same applies to all the other static `Default*` fields on `JwtSecurityTokenHandler`.

**Comment by keegan-caruso** [comment]
Thanks for opening an issue.

Not sure what the ask is here? We can't remove the static variables as that is a breaking change.

**Comment by brockallen** [comment]
This has been a long-standing complaint (for 5+ years). I'm sure you can find the other similar issues raised about this.

**Comment by IanKemp** [comment]
> Not sure what the ask is here? We can't remove the static variables as that is a breaking change.

>> Instead there should be an instance configuration method or option that can be hooked in ConfigureServices, i.e. following the standard pattern for configuration in ASP.NET Core.

After that, mark these static fields on `JwtSecurityTokenHandler` as `[Obsolete]` and update the documentation to point people to use the instance properties you're going to create.

> This has been a long-standing complaint (for 5+ years). I'm sure you can find the other similar issues raised about this.

I'd be impressed if that's the case, since `DefaultMapInboundClaims` was added in 6.6.0 which was released a mere four months ago.

Or perhaps you are referring to [this issue](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/278) from 2015 which was also caused by statics. Seems this team hasn't learned since then.

**Comment by brentschmaltz** [comment]
@IanKemp We take backcompat very seriously since we are a middlelayer SDK and have many, many SDK's that build on top of us we cannot and will not knowingly make any breaking changes.

1. Just don't use the flag.
2. We can certainly mark it [Obsolete]
3. We fully agree we made a mistake in the whole claim mapping debacle and are embarrassed by it. 
3. Keep in mind this decision was made when SAML was still widely used and the logic was to make the claims the same so a single authorization policy would make the same decision at the application layer.
5. We did learn from it as we created a replacement, JsonWebTokenHandler, that has no such nonsense.

We wanted to add a single place to turn off the mapping that was simple for users, we added the static flag. Right or Wrong it makes it simple to turn off. There were other ways to turn it off, clear the inbound map: JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

Asp.net has yet to move to using JsonWebTokenHandler which is one reason this issue keeps surfacing.
Our goal is to move forward with JsonWebTokenHandler and JsonWebToken.

@brockallen again, apologies.
