### ISSUE TITLE
Provide CSP 'unsafe-eval' compliant default value for _script

### ISSUE THREAD

**Issue by twenzel** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1564]
The initial value for `AuthenticationProtocolMessage._script` 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/824068adaeb7b158df2b36d8787f689646e715e0/src/Microsoft.IdentityModel.Protocols/AuthenticationProtocolMessage.cs#L43 
requires the CSP value 'unsafe-eval' to be executed. This is a no-go from security perspective.

Please provide a value which does not require this CSP setting:

`<script language="javascript">window.setTimeout(function() {document.forms[0].submit();}, 0);</script>`

**Comment by brentschmaltz** [comment]
@twenzel this code has been here for a long time, has something recently changed?

**Comment by brentschmaltz** [comment]
@twenzel just wanted to mention that AuthenticationProtocolMessage.Script is settable so you can modify an instance with the value you need while we work this out.

**Comment by twenzel** [comment]
> @twenzel this code has been here for a long time, has something recently changed?

No. We just want to enable CSP on our side without the 'unsafe-eval' value.
I wonder why no other having trouble with this.

**Comment by jasonnutter** [comment]
More details: The `setTimeout` function can either take a function callback, or code as a string (which is passed to the `eval` function). As @twenzel notes, usage of `eval` (directly or indirectly) is highly discouraged due to the security risks. I agree with the recommended change in the linked PR to provide a callback instead of code as a string, to allow applications to not have to provide `unsafe-eval` in their CSP headers.
