### ISSUE TITLE
Using JsonWebTokenHandler with ASP.NET Core 5?

### ISSUE THREAD

**Issue by JoeMarkov** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1566]
In ASP.NET Core 5, can I use the fairly new JsonWebTokenHandler  to protect APIs? With AddJwtBearer or similar?

Or what is the usecase for JsonWebTokenHandler?

I find the use of JsonWebTokenHandler vs JwtSecurityTokenHandler very confusing.

**Comment by mafurman** [comment]
At the current moment, it isn't possible to plug in the JsonWebTokenHandler instead of the JwtSecurityTokenHandler.
We plan on adding support for this feature in the future.

Microsoft.IdentityModel.JsonWebTokens library is an updated, more performant, and easier to use version of Microsoft.IdentityModel.Tokens.Jwt that addresses many concerns users had about the previous library. 

I think it would definitely make sense for us to add more documentation on this topic.
