### ISSUE TITLE
Remove JwtRegisteredClaimNames.Name from ClaimMapping

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1627]
Adding this entry:
            { JwtRegisteredClaimNames.Name, ClaimTypes.Name },

Causes a different name to show up in User.Name.

**Comment by oddeirik** [comment]
Is this related to #1619 somehow? We recently had to do a change in an older ASP.NET application after upgrading to 6.9+ where we'd previously used `ctx.AuthenticationTicket.Identity.Name` for UPN lookup. After the upgrade that instead returned the user's name, so had to change it to get the UPN claim specifically (`ctx.AuthenticationTicket.Identity.FindFirst(ClaimTypes.Upn)`.

**Comment by jmprieur** [comment]
@oddeirik : yes, the behavior that changed is you were going a display name instead of the upn / (or preferred_username in Azure AD v2.0 ID tokens)

**Comment by brockallen** [comment]
Please stop making breaking changes in a point release. I don't feel like much consideration is taken for that, and also often a AAD only mindset often seems to justify those changes. This library supports many customers that don't use AAD, so please keep that in mind as changes are considered here.

**Comment by AmyJeanes** [comment]
The change implemented in #1629 looks to have broken our application when upgrading `System.IdentityModel.Tokens.Jwt` from `6.10.0` to `6.10.2`.

We originally had `NameClaimType = "name"` in our `TokenValidationParameters` in `AddJwtBearer` but upgrading from `6.7.1` to `6.10.0` broke it because it looked to now automatically map it to `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name` and no longer set the `name` claim, which was needed for `User.Identity.Name` to work properly.

Then more recently we upgraded again from `6.10.0` to `6.10.2` and now we've found that we needed to re-add the `NameClaimType = "name"` for our application to work as this change removes the mapping again.

Additionally the package is now `6.10.2` on nuget but the latest tag / release on GitHub is `6.10.1` - why is this not been updated? This should at least be mentioned as a breaking change in the release notes.

**Comment by bmmathe** [comment]
Maybe this should be in a different thread but I'm using the `services.AddMicrosoftIdentityWebApiAuthentication(Configuration, "AzureAd");` helper method to configure authentication for my service as suggested in documentation.  I'm also using MSAL 2.0 in my client app to get the access token.  In my [Authorize] controllers User.Identity.Name is null however I can see all the claim (preferred_username) when inspecting the User object.  For whatever reason the NameClaimType mapping is to `http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name` which seems wrong to me.

I also don't see a way to override this name claim type mapping in the `AddMicrosoftIdentityWebApiAuthentication` method.

**Comment by jmprieur** [comment]
@bmmathe you could use User.GetDisplayName() which does its best effort to get a display name

**Comment by brentschmaltz** [comment]
mapping was removed
