### ISSUE TITLE
SecurityTokenException   IDX10222: Lifetime validation failed. The token is not yet valid.

### ISSUE THREAD

**Issue by 785011702** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1658]
我设置的超时时间是1分钟,经常发生这种错误,发生错误后马上重试一次又可以解码,很奇怪
错误消息:IDX10222: Lifetime validation failed. The token is not yet valid. ValidFrom: 'System.DateTime', Current time: 'System.DateTime'.
![image](https://user-images.githubusercontent.com/29771123/123199852-3c0b4100-d4e2-11eb-9b07-e461d32742cf.png)

**Comment by mafurman** [comment]
Do you have IdentityModelEventSoure.ShowPII = false (default setting)?
If so, you should only be able to see the type of the DateTime object, rather than the actual value.

You can see this Wiki page for more information: 
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII

**Comment by brentschmaltz** [comment]
@785011702 please let us know if you have any additional comments.
Closing for now.
