### ISSUE TITLE
API of TokenValidationParameters regarding valid algorithms could be improved

### ISSUE THREAD

**Issue by jsquire** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1706]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET, [#24204](https://github.com/Azure/azure-sdk-for-net/issues/24204).

## Details

**Library or service name.**
`Microsoft.IdentityModel.Tokens`  v6.12.2 and earlier
 
**Is your feature request related to a problem? Please describe.**
This is more of a semantic issue, but the summary for `ValidAlgorithms` is rather rambiguous:
_Gets or sets the valid algorithms for cryptographic operations._
I think it wouldn't hurt if it stated this applies not only to the "alg" claim of the token but also the "enc" claim if applicable. Something like:
_Gets or sets the valid algorithms for signing or encryption operations._

Alternatively, providing additional parameters that check specifically for the respective claims might be even better. For instance:
`ValidSigningAlgorithms`
`ValidEncryptionAlgorithms`

This would also be more compliant with the specs:
- JSON Web Signature: [The "alg" (algorithm) Header Parameter identifies the cryptographic
   algorithm used to secure the JWS](https://datatracker.ietf.org/doc/html/rfc7518#section-3.1). 
- JSON Web Encryption: [The "enc" (encryption algorithm) Header Parameter identifies the
   content encryption algorithm used to perform authenticated encryption
   on the plaintext to produce the ciphertext and the Authentication
   Tag.
](https://datatracker.ietf.org/doc/html/rfc7516#section-4.1.2)

**Comment by brentschmaltz** [comment]
@jsquire i agree with you and find the terminology between "alg" JWS and JWE always requiring a re-read of the spec after some time away.
I think we should first off update the comments.
@ciaozhang can you take care of this.
@jsquire we will leave this issue open for considering adding the two new properties, i marked the item as an enhancement.

**Comment by marwalsch** [comment]
@brentschmaltz Thanks for the considerations; though after a lot of contemplating I started to fear that even two separate properties might not be concise enough. As soon as encryption takes place (i.e. the "enc" parameter is present) the "alg" parameter does no longer refer to the algorithm used for singing, but rather [the algorithm used to encrypt the content encryption key](https://datatracker.ietf.org/doc/html/rfc7516#section-4.1.1). This would make `ValidSigningAlgorithms` not a particularly better option.
 I suggest to either abandon some abstraction and just name the parameters to what they check for, for instance:
`ValidAlgorithmHeaders   ///<Summary>Gets or sets the valid header values for the "alg"-parameter.</Summary>`
`ValidEncryptionHeaders  ///<Summary>Gets or sets the valid header values for the "enc"-parameter.</Summary>`

Or introduce two new sets of options, namely `JweOptions` and `JwsOptions` respectively:

```
public class JweOptions
{
    public string ValidKeyEncrpytionAlgorithms {get; set;}         /// "alg" when JWEs are used, i.e. when "enc" is present
    public string ValidContentEncryptionAlgorithms {get; set;}  /// "enc" values 
}
```

```
public class JwsOptions
{
    public string ValidSigningAlgorithms {get; set;}    /// "alg" when JWSs are used, i.e. when "enc" is not present
}

```

Since `ValidAlgorithms` appears to just check for **any** values present in "alg" or "enc" unconditionally, this does actually not allow for invalid combination of algorithms to be detected. For instance, if I want to accept the following to types of tokens:

- Those merely signed with HS256:
```
{
  "alg": "HS256",
  "typ": "JWT"
}
```

- Those additionally encrypted with RSA-OAEP and A128CBC-HS256:
```
{
  "alg": "RSA-OAEP",
  "enc": "A128CBC-HS256",
  "typ": "JWT"
}
```

Without additional checks any combination of these header values would be appear as valid, despite some of them not making sense or even being against the specs (e.g. "HS256" is only valid for JWS, not JWK). This is the behaviour I made by observation, if this is not the case, forget what I said. 

EDIT:
This goes as far the the API actually accepting tokens who are merely signed with "HS256" and the encryption being entirely ignored upon validation.
Eventually the token gets rejected anyway as secrets are being applied through wrong algorithms which is my this is no real security risk, at least not if one is aware of this behaviour.

**Comment by AndersAbel** [comment]
Please remember when discussion naming that these parameters are also used for Saml tokens, where the terminology is different. Using terms that are JWT-specific would be confusing in that context.

**Comment by marwalsch** [comment]
@AndersAbel You are right, didn't know that. Rather surprising since the service extension itself is called `AddJwtBearer`.

**Comment by keegan-caruso** [comment]
As designed.
