### ISSUE TITLE
UTC and local time 

### ISSUE THREAD

**Issue by jsquire** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1821]
# Issue Transfer

This issue has been transferred from the Azure SDK for .NET repository, [#27417](https://github.com/Azure/azure-sdk-for-net/issues/27417).

## Details

I am working with UTC time as default. The class seems to need `DateTime`s in local system time. It might be helpful to mention this. It was irritating for me.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 39c05e19-5b09-e25e-e49c-9e4486ccb3e1
* Version Independent ID: 63fae4bc-69ee-e638-478e-2fa231431cf9
* Content: [JwtSecurityToken Constructor (System.IdentityModel.Tokens.Jwt) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/system.identitymodel.tokens.jwt.jwtsecuritytoken.-ctor?view=azure-dotnet#system-identitymodel-tokens-jwt-jwtsecuritytoken-ctor(system-string-system-string-system-collections-generic-ienumerable((system-security-claims-claim))-system-nullable((system-datetime))-system-nullable((system-datetime))-microsoft-identitymodel-tokens-signingcredentials))
* Content Source: [xml/System.IdentityModel.Tokens.Jwt/JwtSecurityToken.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/System.IdentityModel.Tokens.Jwt/JwtSecurityToken.xml)
* Service: **active-directory**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by brentschmaltz** [comment]
@iBrotNano we record the values as: DateTime.ToUniversalTime(), so if you are using specifying UTC, you shouldn't have an issue.

see: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/adc8d59d4aaae502f77fd8f758e4f020045f69eb/src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs#L131

Can you provide us with an example that was causing you an issue?

**Comment by iBrotNano** [comment]
Of course.

I created an JwtSecurityToken with a UTC as `expires`.

```c#
var token = new JwtSecurityToken(
    expires: DateTimeOffset.UtcNow.DateTime.AddMinutes(15)
);
```

The problem occurred during authorization in ASP.NET (5.0) via `[Authorize]` attribute.
I am living in Germany. The time zone is UTC+1. 

This is what gets encoded into the JWT:
"exp":1646811645

This ist what gets encoded into the JWT when i configure `DateTimeOffset.UtcNow.ToLocalTime().DateTime.AddMinutes(15)`
"exp":1646815336

The difference is the 60 Minutes of my time zone plus the time it took me to create the two JWTs.

Looking through the code of `ToUniversalTime(DateTime? value)`  i noticed that `DateTimeKind.Utc` ist used. In `DateTimeOffset.UtcNow` the `Kind` is `Undefined` instead of `Utc`. 

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/adc8d59d4aaae502f77fd8f758e4f020045f69eb/src/Microsoft.IdentityModel.Tokens/DateTimeUtil.cs#L98

This results in a call to `value.ToUniversalTime();` instead of just returning the value.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/adc8d59d4aaae502f77fd8f758e4f020045f69eb/src/Microsoft.IdentityModel.Tokens/DateTimeUtil.cs#L115

Maybe it is more a problem with `DateTimeOffset` then `JwtSecurityToken`.

**Comment by brentschmaltz** [comment]
@iBrotNano I am curious why are you specifying .ToLocalTime() above?

**Comment by iBrotNano** [comment]
@brentschmaltz Just to show that using the local time works as expected when the JWT is validated by ASP.NET. `DateTimeOffset.UtcNow.DateTime` does not.

`DateTimeOffset.UtcNow.DateTime.Kind` is `Undefined` so that `ToUniversalTime()` converts the times not correctly. `ToLocalTime()` seems to fix this.

**Comment by brentschmaltz** [comment]
@iBrotNano i invested in writing some code and agree with your observations.
The problem seems to be that DateTimeOffset.UtcNow.DateTime returns a DateTime instance where .Kind == DateTimeKind.Unspecified.
Which seems odd.

It looks other workarounds are:
1. DateTimeOffset.Now.DateTime.AddMinutes(15)
2. DateTime.UtcNow.AddMinutes(15)
3. DateTime.Now.AddMinutes(15)

All three result in the expiration you need.

An obvious change would be to change EpochTime.GetIntData to only apply ToUniversalTime() when DateTime.Kind == DateTimeKind.Local.
This could break existing customers.

I added a new section to our Wiki: [Known Issues and Workarounds](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki)

Which has a link to this page: [DateTimeOffset.UtcNow.DateTime.Kind == DateTimeKind.Unspecified](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/DateTimeOffset.UtcNow.DateTime.Kind-==-DateTimeKind.Unspecified)

I also updated this page: [https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/How-are-DateTime-values-treated%3F](url)
