### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Abstractions, Version=6.18.0.0, Culture=neutral, PublicKeyToken=xxx' or one of its dependencies. The system cannot find the file specified.

### ISSUE THREAD

**Issue by bayerju-ey** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1908]
Using dotnet core 3.1 on Azure App Service (Linux). Existing project works using Microsoft.Identity.Client 4.44.0. Upon upgrading to Microsoft.Identity.Client 4.45.0, project throws the following error:

`System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Abstractions, Version=6.18.0.0, Culture=neutral, PublicKeyToken=xxx' or one of its dependencies. The system cannot find the file specified.`

It appears M.IM.Abstractions is a new dependency of M.I.Client as of 4.45.0. Upon downgrading to M.I.Client 4.44.0, project continues to work as expected. This issue appears similar to #1135. Based on response there, nuspec for M.IM.Abstractions may need to be updated to include netcoreapp2.1 and above. M.I.Client 4.45.0 already includes this. M.I.Client is supposed to be fully compatible with netcoreapp3.1.

**Which version of Microsoft.IdentityModel are you using?**
Microsoft.IdentityModel 6.18 through 6.21

**Where is the issue?**
 * Other (please describe): M.IM.Abstractions 

**Is this a new or an existing app?**
a. The app is in production and I have upgraded to a new version of Microsoft.IdentityModel.*

**Expected behavior**
Microsoft.Identity.Client 4.45.0 should find dependency Microsoft.IdentityModel 6.18.

**Actual behavior**
Exception thrown "System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.IdentityModel.Abstractions, Version=6.18.0.0, Culture=neutral, PublicKeyToken=_xxx_' or one of its dependencies. The system cannot find the file specified."

**Possible solution**
Appears similar to #1135. Nuspec may need to be updated to include netcoreapp2.1 and above.

**Comment by jmprieur** [comment]
@bgavrilMS @pmaytak  FYI. This sounds a p1 to me.
@GeoK, @jennyf19  do you think the issue could come from Wilson?
cc: @TimHannMSFT @sruke @RojaEnnam @dannybtsai @ciaozhang @cesarpayan

**Comment by bgavrilMS** [comment]
@bayerju-ey I'm having trouble reproducing this issue. I tried to create a console app which targets netcoreapp3.1, then added Microsoft.identity.Client and Microsoft.identitymodel.tokens to it: 

![image](https://user-images.githubusercontent.com/12273384/178769121-780c578e-6f30-41cd-bc10-7d866cee52bb.png)


This seems to work fine. Also tried with an ASP.NET Core website with no auth, and it seemed to work. 

To me the problem described in #1135 is different, because .NET Classic + Net Standard do indeed have problems, but I'd expect a netcoreapp3.1 setup to work fine. Can you provide more repro steps, e.g. what dependencies you are using etc.? 

CC @trwalke who did the work in Microsoft.Identtiy.Client

**Comment by bayerju-ey** [comment]
Did some more investigation after you couldn't reproduce. Appears my app isn't correctly picking up that M.I.Abstractions is compatible with netcore; however, I can get my app to detect M.I.A if I do the following:

`cd /root/.nuget/packages/microsoft.identitymodel.abstractions/6.18.0/lib`
`cp -ar netstandard2.0 netcoreapp2.1`

Not sure why my app doesn't correctly detect netcore to begin with, but adding a specific target framework folder in the netcore family causes the app to properly detect it. It would be great if M.I.Abstractions was explicitly tagged in nuget as compatible with netcoreapp frameworks (it's not a target framework in the nuspec file), but I'm fine if you want to close this one as user error since I can work around it. 

Thanks!

**Comment by bgavrilMS** [comment]
You shouldn't need to do this hack, because nuget will figure it out for you. Do not handle dlls on your own.

NuGet uses a concept called "the nearest framework" - https://nugettools.azurewebsites.net/6.0.0/get-nearest-framework

In you case, your app is netcore 3.1 and M.I.Absctrations targets `netstandard2.0`, `net6`, and `net4*` (old .net). The nearest framework is netstndard2. This is because netstandard2 is compatible with netcore- https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0.
