### ISSUE TITLE
Align Nuget package name with aspnet.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#194]
aspnet maps package names with assemblies.

our package names should be: 
Microsoft.IdentityModel.Tokens
Microsoft.IdentityModel.Tokens.Jwt

etc.

**Comment by tushargupta51** [comment]
Our packages on nuget.org have a different naming conventions. e.g.: https://www.nuget.org/packages/System.IdentityModel.Tokens.Jwt/. It should be called Microsoft.IdentityModel.Tokens instead of JSON Web Token Handler For the Microsoft .Net Framework 4.5. Similar changes for the protocol.extensions package.

**Comment by tushargupta51** [comment]
@brentschmaltz As we discussed the other day, the packages name for 5.x are fine. Do we want to change the packages name for 4.x? We can do that the next time we push out a release for 4.x. I will change the labels.

**Comment by brentschmaltz** [comment]
Lets leave them for 4.x. I am hoping that we can use the 5.x branch for all packages.

**Comment by brentschmaltz** [comment]
We are leaving 4.x as is. Changes are in 5.x
