### ISSUE TITLE
[Documentation] an inappropriate url in PII

### ISSUE THREAD

**Issue by powerumc** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#1963]
### Documentation related to component

Wiki Url -  https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/wiki/PII

### Please check all that apply

- [x] typo
- [ ] documentation doesn't exist
- [ ] documentation needs clarification
- [ ] error(s) in the example
- [ ] needs an example

### Description of the issue

By default, we do not include any potential PII (personally identifiable information) in our exceptions in order to be in compliance with [GDPR](https://eugdpr.org/).

`By default, we do not include any potential PII (personally identifiable information) in our exceptions in order to be in compliance with [GDPR](https://eugdpr.org/).`

`https://eugdpr.org` <--- This domain redirect to other domain.

**Comment by brentschmaltz** [comment]
@jmprieur do you know what the correct url should be?
https://gdpr.eu ?

**Comment by powerumc** [comment]
Links on the wiki redirect to other websites.
https://eugdpr.org/ link redirect to https://www.annascosmetics.com/

Please check the link in the wiki.

**Comment by gunr2171** [comment]
How about the Wikipedia page? https://en.wikipedia.org/wiki/Gdpr

**Comment by powerumc** [comment]
https://user-images.githubusercontent.com/1943755/219905865-0f10f298-d2ab-4a34-8ae1-c1e0b97ffa9f.MOV

This correct link?

**Comment by gunr2171** [comment]
If there's some confusion, I deleted my previous comment suggesting a link to the GDPR Wikipedia page. I did this because I though that brentschmaltz's link was the same as what is currently on the wiki page.

The difference here is a slight difference in the domain, eugdpr.org vs gdpr.eu. Unfortunately I was too slow in realizing the difference, hence the post-then-delete. Sorry about that.

[At one time](https://web.archive.org/web/20191104210829/https://eugdpr.org/), eugdpr.org was the correct website for GDPR information, though it seems that around [December of 2019](https://web.archive.org/web/20191218130307/https://eugdpr.org/) it switched ownership, then eventually turned into a redirect to this other personal site.

It does appear that gdpr.eu is funded directly by the European Union, as well as having the [.eu TLD](https://en.wikipedia.org/wiki/.eu) used for EU-connected sites. Pretty safe to say that https://gdpr.eu/ is _now_ the correct site.

**Comment by ciaozhang** [comment]
Fixed the link.
