### ISSUE TITLE
OpenIdConnectProtocolValidator.RequireStateValidation = false does not disable validation

### ISSUE THREAD

**Issue by Tratcher** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#256]
RequireStateValidation = false does not disable state validation. It still requires OIDCMessage.State to be null and OIDCVlaidationContext.State to be null.

**Comment by Tratcher** [comment]
@tushargupta51 @brentschmaltz

**Comment by Tratcher** [comment]
Actually there's a different problem. This error: `IDX10331: The 'state' parameter in the message: '{0}', does not equal the 'state' in the context: '{1}'.` is being thrown from the wrong places:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs#L228
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Protocols.OpenIdConnect/OpenIdConnectProtocolValidator.cs#L272

**Comment by PinpointTownes** [comment]
I'm tempted to say the current behavior is the right one from a security perspective. If state validation is disabled, you shouldn't be able to specify a state... since allowing any `state` parameter without comparing it to the expected value would open your app to impersonation attacks. That said, the new name is a bit weird, `RequireState` was much more appropriate.

**Comment by tushargupta51** [comment]
@Tratcher You are right. The error message is incorrect. I will push out a fix for that soon.

**Comment by tushargupta51** [comment]
I agree with @PinpointTownes on the better name. RequireStateValidation is bit misleading.

RequireState:
If this is set to true:
1. All requests sent to IDP and responses received from IDP must have state and they must match, otherwise protocol validator will throw.

If this is set to false, it allows you to send requests without any state.
1. If state is missing in the request but IDP sent a response with the state, then something is wrong, protocol validator will throw. It's more of a safety net.
2. If state is present in the request (which is allowed even when RequireState is false), but IDP did not send the state in response, protocol validator will throw since there is definitely something wrong.
3. If state is not present in the request as well as response, it will pass thru.

I remember, in the last meeting, there was a requirement about having a flag that asp.net can use to take over the state validation (because they do their own correlation id validation) and that is why I renamed it to RequireStateValidation. Though, the behavior of that flag was more like "RequireState" as I explained above. And this is what is causing the grief, I guess.

@Tratcher The validation that we do is merely a string comparison. Is is possible for you to set the correlation ids (I dont knw how that works) in the context before you call the protocol validation. Or is there a need for another flag "RequireStateValidation"?

cc @brentschmaltz

**Comment by tushargupta51** [comment]
@Tratcher How about having 2 flags: RequireState (as described above) and RequireStateValidation. If RequireStateValidation is set to false, we dont try to validate state at all.

Does it sound like an overkill? Both defaults to true. All you need to do is set RequireStateValidation to false on protocol validator, no need to deal with RequireState flag in that case.

**Comment by Tratcher** [comment]
@tushargupta51 I want what you described as RequireStateValidation. I don't think RequireState has much value beyond that, but as I won't use it I don't care one way or the other.
