### ISSUE TITLE
Matching jwt token against a regex

### ISSUE THREAD

**Issue by tushargupta51** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#262]
When creating a JwtSecurityToken from a json string, we match it against a regex. Investigate whether that matching is required or just validating the max length of token and base64 decoding is good enough.

**Comment by tgitchel** [comment]
To allow for base64 encoded JWT with equals signs and RS256 signatures, the JsonCompactSerializationRegex in JwtConstants.cs should be set to:

        /// <summary>
        /// Token format: 'header.payload.signature'. Signature is optional, but '.' is required.
        /// </summary>
        public const string JsonCompactSerializationRegex = @"^[A-Za-z0-9-_=]+\.[A-Za-z0-9-_=]+\.?[A-Za-z0-9-_.+/=]*$";

The comment says that the second period is required, but my reading of the spec says otherwise, so the above regex allows for optional second period.

7.2. Validating a JWT

When validating a JWT, the following steps are performed. The order of the steps is not significant in cases where there are no dependencies between the inputs and outputs of the steps. If any of the listed steps fail, then the JWT MUST be rejected -- that is, treated by the application as an invalid input.

    Verify that the JWT contains at least one period ('.') character. 

To handle this condition, JwtSecurityToken.cs Decode method could be modified to append trailing period, of there is only one present:

       /// <summary>
        /// Decodes the string into the header, payload and signature
        /// </summary>
        /// <param name="jwtEncodedString">Base64Url encoded string.</param>
        internal void Decode(string jwtEncodedString)
        {
            if (jwtEncodedString.Split(new char[] { '.' }).Length == 2)
            {
                jwtEncodedString += ".";
            }
            string[] tokenParts = jwtEncodedString.Split(new char[] { '.' }, 4);

**Comment by tushargupta51** [comment]
We are past RC1, pushing it to RC2.

**Comment by tgitchel** [comment]
This seems like a pretty critical bug to me.  There are many correctly formatted tokens that currently cannot be read or validated by the JwtSecurityTokenHandler (and incorrectly formatted tokens that will pass).
What is the timeframe for RC2?

**Comment by tushargupta51** [comment]
@tgitchel RC2 is scheduled for early Feb 2016. We got to know the tentative dates yesterday only.

**Comment by tushargupta51** [comment]
The original issue was to investigate whether we need to have regex or not. If we do, then what should be the default timeout? Based on our discussion, it seems that we need the regex to find out if the incoming token is a valid base64url encoded string before we actually try to decode it because of perf reasons. Also, we changed the default timeout to be 100 ms from 2 s. We don't think there is a need to have this setting configurable. 100 ms looks good. Closing this issue as fixed. @brentschmaltz
