### ISSUE TITLE
[Bug] Fix flaky tests: NameAndRoleClaimDelegates and RoleClaims in System.IdentityModel.Tokens.Jwt.Tests.CreateAndValidateTokens

### ISSUE THREAD

**Issue by jennyf19** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#2841]
More flaky tests, run with all the tests and they fail, run individually and they pass:

`System.IdentityModel.Tokens.Jwt.Tests.CreateAndValidateTokens.NameAndRoleClaimDelegates`

AND:
`System.IdentityModel.Tokens.Jwt.Tests.CreateAndValidateTokens.RoleClaims`
   Source: CreateAndValidateTokens.cs line 1081
   Duration: 5 ms

  Message: 
Assert.True() Failure
Expected: True
Actual:   False

  Stack Trace: 
CreateAndValidateTokens.CheckForRoles(IEnumerable`1 expectedRoles, IEnumerable`1 unexpectedRoles, ClaimsPrincipal principal, String expectedRoleClaimType) line 1250
CreateAndValidateTokens.RoleClaims() line 1098

**Comment by msbw2** [comment]
The latest version of `dev` doesn't repro this issue anymore. I suspect #2859 may have fixed this one as well.

**Comment by kllysng** [comment]
When run individually, the tests pass. 

When run with other tests, they both fail - on `Assert.True(principal.IsInRole(role));`. When investigating:
- `ClaimsPrincipal.IsInRole()` checks the values both the Role Claim Type and value.
- When failing, the claim role type is `Role`.  Stepping through, the claim type starts out as `http://schemas.microsoft.com/blah/blah/blah/claims/role` and is changed into `Role`. 
- When passing, the claim role type is mapped into the long name. Stepping through, the claim type again starts out as the long name, changes to the short one, and is mapped back into the long form name. 
- Finally, when passing: 
![image](https://github.com/user-attachments/assets/e3c1cf58-2354-4a55-97e2-a169c0725104)
- and when failing:
![image](https://github.com/user-attachments/assets/8a8ba0a7-30f7-4c88-866a-803c68e7eb45)

I was confused, because `_mapInboundClaims` is not static, neither is `MapInboundClaims`. But then, I saw that `_mapInboundClaims` was initialized equal to `DefaultInboundClaims`.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/7f90e3475e483b7fc1d1d19c658138b48d05de66/src/System.IdentityModel.Tokens.Jwt/JwtSecurityTokenHandler.cs#L47

In this other test, `MapInboundClaims`, I see that we:
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/7f90e3475e483b7fc1d1d19c658138b48d05de66/test/System.IdentityModel.Tokens.Jwt.Tests/JwtSecurityTokenHandlerTests.cs#L1135

I propose that we do not modify statics this way in our tests.
