### ISSUE TITLE
Review the implementation of IDisposable.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#288]
We used to dispose just the 'hash' but we create other disposable objects.

**Comment by tushargupta51** [comment]
We need to review if there are classes that need to implement IDisposable. For example, SecurityKey is one such class.

**Comment by tushargupta51** [comment]
We need to implement `IDisposable

**Comment by tushargupta51** [comment]
We need to implement `IDisposable` if a class
1. is creating unmanaged resources
2. is creating objects that implements IDisposable. It's important to note that class is responsible for disposing only the objects it OWNS. It should not dispose objects that it did not create.

We do not create/use any unmanged resources in our code. So, we only considered Point 2 to determined whether a class should implement `IDisposable` or not. We found that we do not need to implement `IDisposable` in `SecurityKey` class, since these classes do not create any disposable objects. Also investigated all other classes in our library and made sure we are not missing anything. The only place where a change is needed was `HttpDocumentRetriever` class where we create a new `HttpClient` object. That has been fixed in the related PR.
