### ISSUE TITLE
Should AuthenticationProtocolMessage constructor take a string ? 

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#289]
This blocks passing a 'json' string to the constructor and forces users to convert to JsonObject first.

**Comment by tushargupta51** [comment]
@brentschmaltz I am going to investigate why we have the AuthenticationProtocolMessage.ctor that takes a string issuer address? What scenario does it support?

**Comment by tushargupta51** [comment]
@brentschmaltz @RandalliLama I don't see any specific need to have a ctor to set the IssuerAddress property only. We can get rid of it. But if we change the ctor that takes a 'JObject' to the one that takes a 'json string', it will be breaking changes for asp.net guys since they are using our 'JObject' ctor that we added in Rc1.

**Comment by tushargupta51** [comment]
Moving this to RC2. We will keep the constructor that takes 'JObject' so its not a breaking API change. Instead, we will modify the existing 'stirng' ctor to interpret the string as json instead of issuerAddress. and move that ctor from AuthenticationProtocolMessage to OpenIdConnectMessage.
