### ISSUE TITLE
Re-introduce a SecurityAlgorithms/JwtAlgorithms mapping table

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#316]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/300#issuecomment-157877007

/cc @brentschmaltz

**Comment by tushargupta51** [comment]
@PinpointTownes @brentschmaltz 
I think we have consensus on having an outbound mapping (which means jwt generated by this library will have short alg names).

I and @brentschmaltz felt that we do not need an inbound mapping because the signature providers do not need to distinguish between a jwt alg or a xmldsig alg. As long as it knows how to handle both algorithms, it should be good. And what it supports is reflected by `IsSupported` method.

**Comment by brentschmaltz** [comment]
@PinpointTownes @tushargupta51 Some background on why the mapping was originally needed. In 4.x and previous versions of Wilson, Algorithm logic such as: IsSupportedAlgorithm, GetHashAlgorithm, were delegated to the SecurityKey in System.IdentityModel.dll. Those SecurityKeys only understood certain algorithms. For example an X509AsymmetricSecurityKey would not understand RS256. Since RS256 and http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 are the same, we needed to map. 
With our new model of viewing the SecurityKey as:
1. a bunch of bits
2. a wrapper for a CryptoProvider (think constructor RsaSecurityKey(RSA))
We don't need the mapping as our CryptoProviders understand that RS256 == http://www.w3.org/2001/04/xmldsig-more#rsa-sha256 and will do the right thing.

**Comment by tushargupta51** [comment]
@brentschmaltz @PinpointTownes where have we landed with this?

**Comment by PinpointTownes** [comment]
Sadly, nowhere. And it's still somewhere we **absolutely need**, specially since XMLdsig and JWA identifiers have been merged in the same class (`SecurityAlgorithms`).

**Comment by polita** [comment]
Because we only support JWT right now, we will consider this when we reintroduce SAML.

**Comment by PinpointTownes** [comment]
Fantastic, and in the meantime... https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/400

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/447
We addressed outbound mapping in: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/447
