### ISSUE TITLE
Revert the changes applied to AsymmetricSecurityKey

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#330]
In IdentityModel 5, `HasPrivateKey` and `HasPublicKey` are now properties (instead of methods). 

Though it's not currently an issue as `RsaSecurityKey` and `ECDsaSecurityKey` only accepts key materials (see https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/325), fixing these classes to directly accept `RSA` and `ECDsa` will likely require implementing more elaborated `HasPrivateKey` and `HasPublicKey` implementations to determine whether a private key is available or not, which may have an important CPU/IO cost (when a HSM is used, for instance).

Using methods here would be much more appropriate.

/cc @brentschmaltz

**Comment by tushargupta51** [comment]
@PinpointTownes In a recent PR, I added ctors that take `RSA` or `ECDsa` instances when creating the `SecurityKey`. Though in those cases, because of the cost involved in fake signing to determine whether the key is private or public only (especially for hardware keys), we set the HasPrivateKey property to true and let it fail later at the time of signing.

**Comment by tushargupta51** [comment]
@PinpointTownes @brentschmaltz 
I was debating on whether `HasPrivateKey` should be a property or a method. Based on the guidelines here (https://msdn.microsoft.com/library/ms229054(v=vs.100).aspx), I think a property sounds more appropriate because of the following:
1. The value of the property does not change between calls unless the instance holding the property changes.
2. Though you can argue it could be computationally expensive in case of hardware keys because of fake signing, the effect is not profound since it is only done once per instance and for later calls the stored result is returned, which indicates more of a property behavior.
3. The getter does not generate any potential side effect, it only sets the value of the private variable  _hasPrivateKey.

Also, I am considering removing `HasPublicKey` method from `AsymmetricSecurityKey` since that does not add much value for an asymmetric key which are supposed to almost always have the public key. Also, in current implementation, the API always tends to return true or determine the result based on HasPrivateKey attribute.

**Comment by PinpointTownes** [comment]
> Though you can argue it could be computationally expensive in case of hardware keys because of fake signing, the effect is not profound since it is only done once per instance and for later calls the stored result is returned, which indicates more of a property behavior.

Well, the rule is clear: accessing a property is not supposed to be slow, even if it just impacts the first call.

> The operation is orders of magnitude slower than a field set would be. If you are even considering providing an asynchronous version of an operation to avoid blocking the thread, it is very likely that the operation is too expensive to be a property. In particular, operations that access the network or the file system (other than once for initialization) should most likely be methods, not properties.

Another argument in favor of the method is that it would avoid a breaking change between desktop and CoreCLR if you merged the two targets.

______

> Also, I am considering removing HasPublicKey method from AsymmetricSecurityKey since that does not add much value for an asymmetric key which are supposed to almost always have the public key. Also, in current implementation, the API always tends to return true or determine the result based on HasPrivateKey attribute.

Agreed, this property is useless (I still can't figure out why it was introduced :smile:)

**Comment by tushargupta51** [comment]
@PinpointTownes It's not just about the performance of the property getter, the property value does not change between calls. It does not seem to be black and white decision between property and method, it can go either way. Property seems a better option to me in this case. BTW, the performance hit (in the first call) is only an issue when it is a hardware bound key, which is going to be subset of all use cases.
For the breaking change, we are not sure yet when these classes are going to be merged to dotnet, if at all. If System.IdentityModel is ported to clr, am not sure what the behavior of SecurityKey class is going to be like.
