### ISSUE TITLE
Reintroduce ClaimsIdentity.Actor support via SecurityTokenDescriptor

### ISSUE THREAD

**Issue by PinpointTownes** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#361]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/327#issuecomment-162992208

**Comment by brentschmaltz** [comment]
@PinpointTownes excellent timing :-) as I was about to see if you had an opinion on if we should scrap the OM that uses IEnumerable<Claim> and go back to ClaimsIdentity on SecurityTokenDescriptor and CreateJwt(....). It does force users to create a ClaimsIdentity when all they want to pass are claims.


(proposing a rename below)
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/363

**Comment by PinpointTownes** [comment]
Sounds like a good idea :+1:

**Comment by brentschmaltz** [comment]
@PinpointTownes It would affect a lot of tests, would you be OK if we make this in the next milestone as we are trying to get RC2 out.

**Comment by PinpointTownes** [comment]
I'm fine :smile: (even if breaking changes like this one should be added very early to avoid breaking too many people with the next release).

**Comment by brentschmaltz** [comment]
I agree, early is better. I'll try and get it in, we have other teams taking a dependency so we need to get done soon.
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/360 seems more important.

**Comment by JohnGalt1717** [comment]
As it stands because of this and other issues you've got rogue nuget packages floating around that show up to automatically update any .NET 4.5+ solution but if you do, there is no way of getting the same functionality in alternative ways because of stuff that you've not included that falsely reports it should be there. (i.e. try creating openidconnect login support in mvc.net right now, you can't with these.

Given this is about the 10th such instance of .net core "upgrades" completely destroying .net 4.x full fat projects because of your nuget packages and your lack of testing and thought on .net full you guys need to get in a meeting immediately and fix the way you're doing this stuff:

1. If you're not providing the same functionality as the previous version AND not providing an alternative then you MUST NOT claim compatibility in your nuget package with .NET full.
2. If case #1 is true, then you SHOULD be creating a separate nuget package.

But you should consider anything that breaks .NET full functionality as  BLOCKER because azure dlls and just about all of the new stuff coming out is .net standard and depending upon these libraries and you're cutting off .NET Full users even though .NET Standard says that it's supposed to work in .NET 4.6 etc. Thus you're NOT actually .NET standard compatible because of these massive breaking changes (System.Net.Http was almost a year before you guys finally got around to fixing the cluster f* that you created!).

It is completely unacceptable that your customers have to deal with this mess. Get it right and don't release until you're not breaking something without a way of getting it back.  This is non-optional or you're going to start losing customers.

**Comment by brentschmaltz** [comment]
@JohnGalt1717 are you speaking about the IdentityModel packages? How are they updated with .net core updates?

**Comment by JohnGalt1717** [comment]
System.IdentityModel.Tokens.Jwt 5.1.2 is explicitly for .NET Standard and used by a ton of .net standard libraries. (and Microsoft.IdentityModel.Tokens, and Microsoft.IdentityModel.Protocol.Extensions)

These updates (as outlined in other github comments) have completely broken .NET Full's IdentityFramework infrastructure specifically because MS doesn't want to open source some SAML2 stuff. The result is complete chaos. And guess what? This isn't the first time this has happened with these packages being updated and breaking .NET Full for the sake of .NET Standard.

**Comment by JohnGalt1717** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/327#event-982189447

**Comment by JohnGalt1717** [comment]
Also Microsoft.IdentityModel.Logging

(And Previously System.Net.Http amongst others)

**Comment by brentschmaltz** [comment]
@JohnGalt1717 I reopened 327. 
`because` MS doesn't want to open source some SAML2 stuff. 

 Are you speaking about SamlTokens?

**Comment by brentschmaltz** [comment]
@JohnGalt1717 it sounds like a Katana project is trying to use the 5.x version. That wont work right now.

**Comment by JohnGalt1717** [comment]
That's the point. You've released updated nuget packages that perport to support .net full and guess what? They don't.

I just spent a day and a half undoing the mess from nuget automatically updating these by accident because I updated another nuget package that now depends on V5 stuff.

Either remove .net full support from this until you have your stuff straight or create a new nuget package separately.
