### ISSUE TITLE
IdentityModel serialization/deserialization process issue

### ISSUE THREAD

**Issue by stephenstroud** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#365]
Using JWT with openIdConnect latest rc2.

when my claim leaves the service it appears like:
http://schemas.microsoft.com/ws/2008/06/identity/claims/role: user
but on return it looks like:
http://schemas.microsoft.com/ws/2008/06/identity/claims/role: "user"

It has added some extra quotes along the way

so I can't validated with something like
principal.HasClaim(ClaimTypes.Role, "user");

This is only happening with an array of claims.

**Comment by PinpointTownes** [comment]
@brentschmaltz @tushargupta51 we suspect the bug might be caused by the recent changes in the JSON serialization/deserialization process: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/commit/6cefb7cf902abdfb594fb785f30bec8e5af4059b.

**Comment by PinpointTownes** [comment]
The bug is likely caused by this line: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/System.IdentityModel.Tokens.Jwt/JwtPayload.cs#L349

Since there's no special case for string, `JsonExtensions.SerializeToJson` is called with the string value, which adds the quotes you're seeing (`value` -> `"value"`).

**Comment by brentschmaltz** [comment]
@stephenstroud @PinpointTownes thanks guys. Will get right on this. Hope to get a fix out tonight. asp.net will pick up the fix for RC2.

**Comment by brentschmaltz** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/368
