### ISSUE TITLE
Various namespace problems

### ISSUE THREAD

**Issue by Grimz0r** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#519]
I was trying to use v5.0.0 (got from nuget today) and It's so SOOO painful. Sometimes it "needs" objects form System.IdentityModel.Tokens, other times it's Microsoft.IdentityModel.Tokens and most of the time there are classes on both namespaces w/ the same name!

Example:
you can create a SecurityTokenDescriptor like this

var securityTokenDescriptor = new SecurityTokenDescriptor()
            {
                AppliesToAddress = "http://my.website.com",
                TokenIssuerName = "http://my.tokenissuer.com",
                Subject = claimsIdentity,
                SigningCredentials = signingCredentials,
            };

![screenshot_1](https://cloud.githubusercontent.com/assets/9133888/19494176/9614748e-955c-11e6-999d-54d505cc3a46.png)

and a JwtSecurityTokenHandler like this
var tokenHandler = new JwtSecurityTokenHandler();
![screenshot_2](https://cloud.githubusercontent.com/assets/9133888/19494185/a4d304ea-955c-11e6-871f-9a95ff378543.png)

both are from the same namespace, but when you try to do this 

var plainToken = tokenHandler.CreateToken(securityTokenDescriptor);
you get
Error	CS1503	Argument 1: cannot convert from 'System.IdentityModel.Tokens.SecurityTokenDescriptor' to 'Microsoft.IdentityModel.Tokens.SecurityTokenDescriptor'

![screenshot_3](https://cloud.githubusercontent.com/assets/9133888/19494198/c428c8f2-955c-11e6-9654-a0cf90fc7095.png)

**Comment by brentschmaltz** [comment]
@Grimz0r are you linking System.IdentityModel.dll (the .Net 4.5 version)? If so you will need to fully qualify types. You can do this at the top of a file.  

// project references since we are in the System ns, we need to map to M.IM.Tokens
using TokenDescriptor = Microsoft.IdentityModel.Tokens.SecurityTokenDescriptor;

.....

var tokenDescriptor = new TokenDescriptor(...)
tokenHandler.CreateToken(tokenDescriptor)

....

There are name collisions between M.IM.Tokens.dll and System.IdentityModel.dll. We put the supporting artifacts for S.IM.Tokens.Jwt in the M.IdentityModel.Tokens namespace so that users could include System.IdentityModel.dll using the

**Comment by brentschmaltz** [comment]
@Grimz0r if this does not work for you please reopen.
