### ISSUE TITLE
Complete Json serialization extensibility

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#54]
JSon serialization / deserialization and creation of claims takes a hard dependency on NewtonSoft throughout the stack. If a user wishes to use a different serializer, it would be difficult to do so. 
We need to examine the stack and ensure extensibility is possible.

See: 
1. JwtPayload.Claims
2. JsonWebKey constructor
3. JsonWebKeySet constructor
4. ConfigurationManager

**Comment by tushargupta51** [comment]
@brentschmaltz Currently, usage of newtonsoft is embedded in a way that it is difficult to override the default json de/serialization. For example, we have ctors in OIDCMessage, JsonWebKey, JsonWebKeySet that uses JsonConvert to deserialize the json. Users have to override these classes to hook in their own ctors which uses a different serializer which is obviously a pain.

Another usage is in JwtPayload.Claims and OIDCConfigurationRetriever. JwtPayload.Claims is a virtual, users can override it to deserialize the json claim.  OIDCConfigurationRetriever is a difficult one since the GetAsync method that converts the json metadata is not virtual, though they can hook in their own retriever in configurationManager.

So, there are ways for users to override newtonsoft but they are definitely NOT easy to implement. But am not sure about how much we want to surface this extensibility point given Newtonsoft.json is a very popular library that a lot of people uses and it does provide a good set of features and functionality.

**Comment by RandalliLama** [comment]
This is going to be too invasive for not enough benefit. It also seems like a mostly additive change that we could add when we know that there is actually demand for it.
