### ISSUE TITLE
SignatureProviderFactory should have a check for maximum size on keys

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#57]
CreateProvider should check the maximum size of the key. this helps mitigate DOS attacks where large key sizes are specified.

**Comment by tushargupta51** [comment]
@brentschmaltz In .net, all algorithms implement legal key sizes (ECC might not), and they make sure at the the time of signing or verifying, that the key size is less than the maximum allowed. Should we have this property in Wilson? I say no since its going to prevent the DOS attack at .net layer, the only gain from having it in wilson is that we will fail at the time of creating signature providers. Also, having static defaults here like the way we have for min key sizes is probably not a good idea, what if the max key sizes changes in .net (not sure how likely is that).

**Comment by RandalliLama** [comment]
I agree completely. I don't know why we would do this.
