### ISSUE TITLE
There are reports that KB4025344 breaks 4.x

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#657]
see here:

https://github.com/IdentityServer/IdentityServer3/issues/3790

Any idea whats going on?

**Comment by brentschmaltz** [comment]
@leastprivilege I have seen that, I haven't dug into it yet. It looks like a SHA2 issue.
I believe CoreFx is aware.

@bartonjs any ideas?

**Comment by leastprivilege** [comment]
This happens on plain old .NET with Katana.

**Comment by brentschmaltz** [comment]
@leastprivilege yes I see it is Katana which implies you are using IdentityModel 4.x.
When I mentioned CoreFx above, i see how that was confusing. I wasn't thinking Core, I meant to indicated that the .Net overall team is aware of this issue.
@AlinCiocan responded on #3790 that SHA2 is in play.

**Comment by bartonjs** [comment]
I don't know of any issues which would have been brought about with servicing within either Windows or the BCL.

Since the callstack shows that you're still using using CAPI classes the only thing I can think of is you somehow used to have PROV_RSA_FULL to PROV_RSA_AES liftup code and it's no longer running; but that'd be something in idfx code.

There's definitely not anything that the BCL is working on here.

**Comment by andreea-anastasescu** [comment]
We are using Identity Server 3 for one of our customers, the application being hosted in cloud, on an Azure Cloud Service. Are there any chances that a similar service pack to be installed on the hosting servers?

**Comment by brentschmaltz** [comment]
@leastprivilege we haven't close this, i stopped tracking it because I saw that changing the version to .net 4.6.2 (I think) solved the issue. Do you need this investigated further?

**Comment by brentschmaltz** [comment]
this should be fixed with https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/pull/813 with 5.2.0. An upgrade to Katana will be necessary.
