### ISSUE TITLE
Issue generating tokens with a certificate on full framework

### ISSUE THREAD

**Issue by javiercn** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#667]
I'm trying to generate a JWT token using a certificate as signing credentials and I'm getting an exception from the JwtSecurityTokenHandler.

It seems that it's calling the wrong .net framework api to get the private key.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/master/src/Microsoft.IdentityModel.Tokens/X509SecurityKey.cs#L92

The api below throws an exception _certificate.GetRSAPrivateKey() returns the key correctly.

[CertificateRepro.zip](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/files/1201974/CertificateRepro.zip)

**Comment by brentschmaltz** [comment]
@javiercn unfortunately this API (GetRSAPrivateKey) is not available on 4.5.x. 
We need to rethink how to get the private key for different targets. We may need a new target for 4.6.x needs a new target.

**Comment by brentschmaltz** [comment]
@lovemaths we should get this fixed with https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/480

**Comment by brentschmaltz** [comment]
@lovemaths we GetRSAPrivateKey() was introduced in 4.6. 
Can we find a way to determine if _privateKey = RSACertificateExtensions.GetRSAPrivateKey(_certificate) exists? Either by finding out the actual runtime version OR runtime info. RuntimeInfo is richer on Desktop that Core (reflection)

**Comment by lovemaths** [comment]
@javiercn What are your environment and the details of the exception you got? You repo runs fine on my windows machine.

**Comment by javiercn** [comment]
@lovemaths the test is disabled on full framework. I’ll give you a branch you can use tomorrow.

The easiest thing to do would be to add a netstandard2.0 target in the library.

**Comment by javiercn** [comment]
@lovemaths You can clone the repo and comment this line
https://github.com/aspnet/Identity/blob/dev/test/Microsoft.AspnetCore.Identity.Service.FunctionalTests/TraditionalWebApplicationTests.cs#L23
When you run the tests it will fail.

**Comment by lovemaths** [comment]
@javiercn I am not able to build the repo from visual studio 2017, using build command in command line also doesn't work. How do I build it and run the test? 

I am not sure why adding a netstandard2.0 target would make a difference. If the test is targeting at netstandard 2.0, and picking up our netstandard 1.4 assemblies, the test will call the code between #if NETSTANDARD1.4 and #else, i.e. "_privateKey = RSACertificateExtensions.GetRSAPrivateKey(_certificate);", since only this part of the code was compiled into the assembly. Why would it call "_privateKey = _certificate.PrivateKey;"?

What is the exception you got?

**Comment by brentschmaltz** [comment]
@javiercn we fixed this in 5.2.4 for RsaSecurityKey. We will be extending this fix and adding additional ECDSA and X509Certs.

https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/877
