### ISSUE TITLE
New Saml1.1 token handler strips the attribute namespace during token validation

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#726]
which means the result ClaimsIdentity will only have claims that use the attribute name for the claim type - the attribute namespace is missing.

This is a radical change from the .NET Framework version of the token handler - and will make migration hard.

**Comment by leastprivilege** [comment]
You also seem to change the SAML authentication method claim to amr - 

I thought we had this discussion already (many times). Leave those claim types alone.

**Comment by brentschmaltz** [comment]
@leastprivilege we are working to do that, we are not quite done yet.

**Comment by brentschmaltz** [comment]
@ChenYan98 can you have a look into this, does https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/668 need additional work?

**Comment by ChenYan98** [comment]
According to my understanding, this is the bug we already found in #668 and it has been fixed in current code. @leastprivilege can you please check if the following code is what you are talking about. https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/668b50de3d8ad77e7b3f5dceb0ee79768c6e5104/src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSerializer.cs#L329
and https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/dev/src/Microsoft.IdentityModel.Tokens.Saml/Saml/SamlSecurityTokenHandler.cs#L661

**Comment by ChenYan98** [comment]
@leastprivilege Let me double check, if you are using preview1? This code has been updated to dev branch couple days ago. You can get the last assembly from our daily build.
