### ISSUE TITLE
Add proof-of-possession support for Saml and Saml2 tokens

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#860]
Currently only 'Bearer' is supported.

**Comment by AndersAbel** [comment]
AFAIK there is no term `proof-of-possession` in the SAML2 standard. Do you mean the `holder-of-key` subject confirmation method? That is something that I think is hardly ever used. Do you have a specific case that you want to support that prompts for adding it? If not, I think there are other things that are more valuable to work on.

**Comment by brentschmaltz** [comment]
Yes. Holder-of-key. This is a gap from previous releases. I want to make sure all such items are recorded whether we do them or not.

**Comment by AndersAbel** [comment]
A first, defensive step, would be to make an implementation that by default throws an exception if a holder-of-key assertion is encountered. Since they are so rare, it's easy to assume that an incoming assertion is a bearer assertion and just apply it to the holder of the assertion.

What about a flag `AllowNonBearerTokens` in the TokenValidationParameters? The name should be one that works with other protocols as well and "bearer" is a general term that several protocols use.

The risk that I see is that while a bearer token is typically tightly guarded and only issued to the right holder, there is not the same need for a holder-of-key token as it provides no value in itself (especially if it is encrypted). So there might be a way for an attacker to gain access to a holder-of-key token for someone else. If that token is later incorrectly treated as a bearer token, the attacker could impersonate a victim.

**Comment by brentschmaltz** [comment]
@AndersAbel it may make scoped to put such flags into the SamlTokenHandlers (1 and 2) as this is SamlSpecific.

**Comment by brentschmaltz** [comment]
@AndersAbel I am convinced we don't need this.

**Comment by AndersAbel** [comment]
@brentschmaltz I think it's okay to not support non-bearer subject confirmation out of the box. But, there should be a possibility to implement custom confirmations. That's possible by overriding `Saml2SecurityTokenHandler.ValidateConfirmationData`.

But I think that there should be a guard in `Saml2SecurityTokenHandler.ValidateConfirmationData()` to reject anything but `urn:oasis:names:tc:SAML:2.0:cm:bearer`.

So my take is to reopen this (or create another issue) to implement that guard.
