### ISSUE TITLE
Allow working with custom point in time in Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime

### ISSUE THREAD

**Issue by fabicz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#874]
We would like to validate token against custom point in time. 

`ValidateLifetime` method works with hardcoded `DateTime.UtcNow`. Would be nice to allow having optional custom DateTime to which to validate possibly to be passed inside `TokenValidationParameters`.

**Comment by brentschmaltz** [comment]
@fabicz can you make use of the delegate: https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/rel/5.2.0/src/Microsoft.IdentityModel.Tokens/TokenValidationParameters.cs#L80 . If set on TokenValidationParameters this will be called when it's time to check lifetime.

**Comment by fabicz** [comment]
I kind of have this approach right now, but I had to copy rather hefty content of the `ValidateLifetime` method and I could not use `LogMessages` because its internal. The trouble was also how to pass the point in time itself to delegate. In the end I call `ValidateToken` and just after that I call the my past&copied `ValidateTokenLifetime`.

**Comment by brentschmaltz** [comment]
@fabicz makes sense, let's shoot for 5.2.2 release.

**Comment by brentschmaltz** [comment]
@fabicz moved issued into 5.2.2 release in April.

**Comment by brentschmaltz** [comment]
@fabicz we ran out of time in 5.2.2 we will get this into 5.2.3

**Comment by fabicz** [comment]
Thanks for update.

**Comment by GeoK** [comment]
@fabicz You should be able to extend _TokenValidationParameters_ class and add your custom DateTime parameter.
Then, you could make use of _TokenValidationParameters.LifetimeValidator_ delegate and implement your custom token lifetime validation logic.

That being said, I'm opening a new issue to address easier addition of custom TokenValidationParameters. #985

**Comment by GeoK** [comment]
@fabicz Not sure if I understand your issue correctly, but if you instantiate the _LifetimeValidator_ delegate then line [L263](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/rel/5.2.4/src/Microsoft.IdentityModel.Tokens/Validators.cs#L263) will not be reached, because of the return at [L253](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/rel/5.2.4/src/Microsoft.IdentityModel.Tokens/Validators.cs#L253).
Please let me know if I am missing something here.

**Comment by fabicz** [comment]
@GeoK yes and because I've to write my own LifetimeValidator, I will copy lines 256 till 273 to my delegate and I need to copy the messages out manually because I cannot use LogHelper.LogExceptionMessage in my own code/package. 

Thats why I was thinking that adding

`DateTime utcNow = validationParameters.ValidationInTime ?? DateTime.UtcNow;`

would solve that easily.

**Comment by GeoK** [comment]
@fabicz  We understand your specific need and we appreciate your suggestion.
However, we won't be adding this feature to the library.
The reason is that the library covers the main scenarios and it provides extensibility to handle other, custom scenarios.

Thank you for the suggestion, and please let us know if we can help further on this.

**Comment by fabicz** [comment]
Ok even though its not optimal for me, I respect that

**Comment by GeoK** [comment]
Thank you. Please take a look at #986 as a _PropertyBag_ will help with your token validation scenario. I'm closing this issue for now.
