### ISSUE TITLE
GetAllSigningKeys provide way to disable?

### ISSUE THREAD

**Issue by b-wins** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#891]
Hi,

JwtSecurityTokenHandler Line 971 - seems like an open flaw here. Why not at least check that jwtToken.header.kid or jwtToken.header.x5t is null first. Or provide a param to somehow disable?

This means we can have a jwtToken with a kid or x5t populated and no corresponding key in issuerSigningKeys, but we still try all possible keys. Is that not a security hole? Do you consider that safe?

**Comment by brentschmaltz** [comment]
@b-wins it's ok to try all possible keys since the application layer added the keys and the signature only validates with the matching asymmetric key. 

GetAllSiginingKeys will be called if the 'kid' in the jwtHeader was not matched to a known key. Since 'kid' can be null, without a match, we try them all.
