### ISSUE TITLE
Protection against changing algorithm fron RS to HS attack

### ISSUE THREAD

**Issue by leastprivilege** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#928]
How do you protect against this attack described in 

https://medium.com/101-writeups/hacking-json-web-token-jwt-233fe6c862e6

in "3. Modify the algorithm RS256 to HS256 (Asymmetric Cipher Algorithm => Symmetric Cipher Algorithm)"

**Comment by brentschmaltz** [comment]
@leastprivilege for this attack to be successful, the run time (TokenValidationParameters.IssuerSigningKey, IssuerSigningKeys OR IssuerSigningKeyResolver) would have to have to serve up symmetric key as one of the keys available for signature validation. Since we partitioned SignatureProviders as Symmetric and Asymmetric, they will throw if an incorrect key type is used.

Most users get public keys from the STS over https, symmetric keys are never used in this flow.

**Comment by leastprivilege** [comment]
OK. thanks
