### ISSUE TITLE
Add in the Microsoft.IdentityModel.Tokens.Jwt library

### ISSUE THREAD

**Issue by mafurman** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#945]
The library should meet the following requirements:

•	Remove automatic short-to-long claim type mapping that occurs when tokens are created.
•	Prepare a framework for future work that will involve asynchronous token validation and creation.
•	Improve the speed of JWT token validation and creation.
•	Simplify the way in which JWT tokens are stored and dealt with.
•	Provide a single extensibility model using delegates. Previous models provided two models: virtual methods and delegates.

**Comment by brentschmaltz** [comment]
library was added

**Comment by EatonZ** [comment]
Is it safe to assume that `JsonWebTokenHandler` is basically the new version of `JwtSecurityTokenHandler`? I've been using `JwtSecurityTokenHandler` and I saw the latest version added `JsonWebTokenHandler`. Is there a reason to use one over the other? Looking over it, it seems the basic difference is encryption support, but I just want some additional clarification here on why this new handler was added.

**Comment by EatonZ** [comment]
Hi @mafurman @brentschmaltz, any insight into the above?

**Comment by brentschmaltz** [comment]
@EatonZ JwtSecurityTokenHandler was modeled after the existing System.IdentityModel.SecurityTokenHandler. There were some compromises that we had to make, such as using System.Security.ClaimsIdentity as the type to build the JWS or JWE when using SecurityTokenDescriptor. ValidateToken had an out parameter, which doesn't for async. 
We then returned a collection of S.S.ClaimsPrincipal, sometimes using claim type mapping. 
This model new model, is much lighter weight and works with native Json.Net objects.
We plan on layering on top, so that you can get back to the existing types, but we will allow users to control what is returned using injection and delegates.

We saw performance improvements of up to 100% in some scenarios.
