### ISSUE TITLE
JwtSecurityTokenHandler needs a way to provide claim filtering / mapping on an instance basis.

### ISSUE THREAD

**Issue by brentschmaltz** [AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet#95]
The current Inbound/OutboundClaimsFilter(TypeMap) are static. This makes it difficult to handle multiple identityproviders etc.
We need a way to set this on a per instance / provider basis.

Perhaps:
1. have a static default
2. introduce a property / delegate on TokenValidationParameters for instance processing

**Comment by damianh** [comment]
:+1:

**Comment by brentschmaltz** [comment]
@damianh Our current pattern is that if a delegate is set on TokenValidationParameters, the delegate has precedence and the default is not called.  Does that seem right to you?

**Comment by damianh** [comment]
Sounds good. May I suggest appropriate info on the xml comments?

I would be argue that the static property should be marked obsolete(false).
It's not something you want to carry forward to vnext either, imho.

Cheers

**Comment by brentschmaltz** [comment]
Mark it obsolete, yet.

I like to follow a pattern of having a 'readonly' property that lets you know the defaults, these are usually statics. For example: DefaultMininumKeySize, then instantiating the instances with these values.

**Comment by damianh** [comment]
+1

**Comment by brockallen** [comment]
Or why not just let the claims come thru as they are in the token and let the application layer deal with them in whatever way it sees fit? This way there's no special coding at all in the library.

**Comment by brentschmaltz** [comment]
@brockallen well, the goal was to 'normalize' between different IdentityProviders and protocols. WsFederation usually uses Saml tokens and longer types for claims than OIDC that uses jwt's but the claims are the really the same type. The authorization-decision-point would be protocol and token agnostic.
I agree, the libraries job is to transform tokens => claims. It is worth thinking about if the handlers should offer transformation.

**Comment by korroz** [comment]
@brentschmaltz Is it a good idea to move claim mapping/filtering to `TokenValidationParameters`?

Wouldn't that also imply that the claim mapping/filtering feature was also effective for `Saml2SecurityTokenHandler`?

I was looking to contribute a bit of code on this issue but as I read the code and looked at the class design I grow uncertain what the better implementation would be.

Another note, creation of the `ClaimsIdentity` is already delegated to `TokenValidationParameters.CreateClaimsIdentity()` so if mapping/filtering parameters are moved to that class anyway wouldn't it be appropriate to perform the mapping/filter in that function?
The caveat is that then it would also affect `Saml2SecurityTokenHandler`.

My thought is that this mapping/filtering really is only the concern of `JwtSecurityTokenHandler` at this moment. But I agree with @brockallen in that claims transformation probably should be left to a higher layer in the application.

**Comment by ghanashyaml** [comment]
I believe that the specific token handlers should be tasked to convert between token types. Reason is that specific token format specifications defines specific claim types supported, so makes sense for the token handlers to handle it. 

If an application handling is saml2 token it would expect token to have longer claim types, so I think the library still is better place to do this conversions.

I also think TokenValidationParameters can do this conversions if it knows about outgoing token format rather than token handlers.

**Comment by korroz** [comment]
I wrote some code that makes instance properties available on `JwtSecurityTokenHandler` for mapping and filtering. I'm not particularly pleased with it myself so I haven't made a pull request, but perhaps I should just to have a place to review and discuss it?

Anyway you can look at the diff of my [jwt-claim-mapping](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/compare/master...korroz:jwt-claim-mapping) branch.

The unfortunate situation where for example the property `InboundClaimTypeMap` is already taken made me name the new property `InstanceInboundClaimTypeMap` which feels a bit messy. I think the actor claims won't be affected right now though, should look into that further. Oh and I added a unit test as well, pretty minimal though.

**Comment by brentschmaltz** [comment]
@korroz @tushargupta51 @ghanashyaml @brockallen We are thinking proposing an all up change to move the statics {outbound / inbound claim mapping, algorithms, etc) to the position of Defaults, then instance methods on the JWT handler.

I am leaning to mapping OFF by default. 
What I am struggling with, is it the Runtime (ASP.NET, WCF, etc) that does the mapping or the Handlers?

thoughts?

**Comment by ghanashyaml** [comment]
My thoughts:
I know this is late to implement but maybe worth considering.
1. There should be a base reference ClaimType which is independent of the token format. For e.g.

class BaseClaimType
{.....
       public const string Email = "Email";
....}

2. Each handler defines its own outbound/inbound mappings and the conversion methods are available as virtual in the base SecurityTokenHandler. This way each handler decides how the claimtypes would be emitted during token creation or interpreted during conversion.

3. Library would not need to maintain multiple ClaimTypeMappings, since each handler provides it own. Currently, JWT has mapping with that of SAML but later on there might be another format coming in. 

4. Library consumers need not worry about using the mappings as the handler would automatically handle it.

So default mapping should be as per decision of tokenhandler. And the mapping should be handled by the handler itself.

**Comment by brockallen** [comment]
Normally we suggest claims transformation middleware to manage things like normalizing the claims.

Or let people do this manually in the notifications callback (which is what we've been doing for the past 2 years w/ Katana anyway to filter out protocol claims).

**Comment by brentschmaltz** [comment]
thanks.
One take away is, let's make the mapping instance rather than per process.

Default mapping: ON of OFF?

**Comment by brockallen** [comment]
Off, please.

**Comment by leastprivilege** [comment]
DEFAULT MAPPING OFF kthxbye ;)

**Comment by damianh** [comment]
off

**Comment by brentschmaltz** [comment]
OK, you got it - OFF by default.

Kudos to Yordan who suggested that years ago :-)

**Comment by korroz** [comment]
Off would indeed be preferred.

So is there any value in my [jwt-claim-mapping](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/compare/master...korroz:jwt-claim-mapping) branch? Or should I perhaps abandon it, knowing that you guys will make a more general sweep of the many statics instead of just claim mapping and filtering?

**Comment by brentschmaltz** [comment]
I would like it if you left it for a while. The code JwtSecurityTokenHandler introducing the 'instance' seems to make sense.

I am not as sure about the JwtPayload as I am thinking 'transformation' seems above the payload.

**Comment by korroz** [comment]
I agree, transformation shouldn't be the concern of `JwtPayload`. I'll see if I can pull that transform logic out of `JwtPayload.AddClaims()` in my branch.

**Comment by korroz** [comment]
I pushed some commits just now on my [jwt-claim-mapping](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/compare/master...korroz:jwt-claim-mapping) branch. In it the transformation logic has been extracted from `JwtPayload`, so now all transforming business is happening in `JwtSecurityTokenHandler`.

Should I create a pull request for further discussion? I still think the code could use a review regarding property names and so on before it can be considered for acceptance, or declined in favor of moving transformation to `TokenValidationParameters`. Whichever way you'd like to go.

**Comment by tushargupta51** [comment]
@korroz Thanks for your work on this. I have created a branch - "claimMapping"(https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/tree/claimMapping) Can you send a PR to that? We are still deciding on how to best tackle this issue and would like to take in your work and build on top of it.

**Comment by tushargupta51** [comment]
@korroz ^

**Comment by korroz** [comment]
Ah, of course. Since your branch is a bit older than `master` though, I have to do some rebase magic before submitting a PR to `claimMapping`. I'll get that done some time today.

And sorry for the late response.

**Comment by tushargupta51** [comment]
@korroz, the claimMappijg branch is based off of KDev branch which is the latest version of wilson. We are planning to fix it in 5.x first and then backport it to 4.x (master branch). I dont think Rebasing will work since these branches are very different from each other. The best way will be to reapply these changes to a branch based on kdev. Sorry for the inconvinience.

**Comment by korroz** [comment]
Ah, I see.

Well rebasing is a flexible tool, and I'm pretty good at it, so I'm sure I can rebase my commits onto `claimsMapping`. Although I see you've switched to *xunit* as well, nice move, I'll convert my code.

**Comment by korroz** [comment]
Rebasing went fairly smooth actually. But installing VS 2015 and making sure the DNX environment was working to actually build and confirm that the rebase was successful took some effort, hehe.

All tests passed and I also signed the cla, so everything should be in order.

**Comment by tushargupta51** [comment]
Fixed in 5.x. Thanks @korroz for your contribution.
